///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CustomerHomeModelDataBoostProfileUserCategoriesSubCategories {
/*
{
  "id": 1,
  "categoryId": 1,
  "name": "Bricklayer",
  "image": "",
  "status": 0,
  "created": 0,
  "modified": 0
}
*/

  int? id;
  int? categoryId;
  String? name;
  String? image;
  int? status;
  int? created;
  int? modified;

  CustomerHomeModelDataBoostProfileUserCategoriesSubCategories({
    this.id,
    this.categoryId,
    this.name,
    this.image,
    this.status,
    this.created,
    this.modified,
  });
  CustomerHomeModelDataBoostProfileUserCategoriesSubCategories.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    categoryId = json['categoryId']?.toInt();
    name = json['name']?.toString();
    image = json['image']?.toString();
    status = json['status']?.toInt();
    created = json['created']?.toInt();
    modified = json['modified']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['categoryId'] = categoryId;
    data['name'] = name;
    data['image'] = image;
    data['status'] = status;
    data['created'] = created;
    data['modified'] = modified;
    return data;
  }
}

class CustomerHomeModelDataBoostProfileUserCategoriesCategories {
/*
{
  "id": 1,
  "name": "Builders",
  "image": "https://app.superinstajobs.com/uploads/1722582520107.6833.png",
  "status": 1,
  "isSubCategories": 1,
  "created": 0,
  "modified": 1722582520
}
*/

  int? id;
  String? name;
  String? image;
  int? status;
  int? isSubCategories;
  int? created;
  int? modified;

  CustomerHomeModelDataBoostProfileUserCategoriesCategories({
    this.id,
    this.name,
    this.image,
    this.status,
    this.isSubCategories,
    this.created,
    this.modified,
  });
  CustomerHomeModelDataBoostProfileUserCategoriesCategories.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    image = json['image']?.toString();
    status = json['status']?.toInt();
    isSubCategories = json['isSubCategories']?.toInt();
    created = json['created']?.toInt();
    modified = json['modified']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['image'] = image;
    data['status'] = status;
    data['isSubCategories'] = isSubCategories;
    data['created'] = created;
    data['modified'] = modified;
    return data;
  }
}

class CustomerHomeModelDataBoostProfileUserCategories {
/*
{
  "id": 2,
  "userId": 2,
  "categoryId": 1,
  "subCategoryId": "4,3,2,1",
  "created": 1738858266,
  "modified": 1738858266,
  "categories": {
    "id": 1,
    "name": "Builders",
    "image": "https://app.superinstajobs.com/uploads/1722582520107.6833.png",
    "status": 1,
    "isSubCategories": 1,
    "created": 0,
    "modified": 1722582520
  },
  "subCategories": [
    {
      "id": 1,
      "categoryId": 1,
      "name": "Bricklayer",
      "image": "",
      "status": 0,
      "created": 0,
      "modified": 0
    }
  ]
}
*/

  int? id;
  int? userId;
  int? categoryId;
  String? subCategoryId;
  int? created;
  int? modified;
  CustomerHomeModelDataBoostProfileUserCategoriesCategories? categories;
  List<CustomerHomeModelDataBoostProfileUserCategoriesSubCategories?>? subCategories;

  CustomerHomeModelDataBoostProfileUserCategories({
    this.id,
    this.userId,
    this.categoryId,
    this.subCategoryId,
    this.created,
    this.modified,
    this.categories,
    this.subCategories,
  });
  CustomerHomeModelDataBoostProfileUserCategories.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    userId = json['userId']?.toInt();
    categoryId = json['categoryId']?.toInt();
    subCategoryId = json['subCategoryId']?.toString();
    created = json['created']?.toInt();
    modified = json['modified']?.toInt();
    categories = (json['categories'] != null) ? CustomerHomeModelDataBoostProfileUserCategoriesCategories.fromJson(json['categories']) : null;
    if (json['subCategories'] != null) {
      final v = json['subCategories'];
      final arr0 = <CustomerHomeModelDataBoostProfileUserCategoriesSubCategories>[];
      v.forEach((v) {
        arr0.add(CustomerHomeModelDataBoostProfileUserCategoriesSubCategories.fromJson(v));
      });
      subCategories = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['userId'] = userId;
    data['categoryId'] = categoryId;
    data['subCategoryId'] = subCategoryId;
    data['created'] = created;
    data['modified'] = modified;
    if (categories != null) {
      data['categories'] = categories!.toJson();
    }
    if (subCategories != null) {
      final v = subCategories;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['subCategories'] = arr0;
    }
    return data;
  }
}

class CustomerHomeModelDataBoostProfile {
/*
{
  "id": 2,
  "name": "Jyoti Builders",
  "email": "jyoti@yopmail.com",
  "phone": "7888644412",
  "profile": "https://app.superinstajobs.com/uploads/1743437099493.0781.jpg",
  "hourlyPrice": 10,
  "dailyPrice": 100,
  "isFav": 1,
  "overallRating": "0.0",
  "userCategories": [
    {
      "id": 2,
      "userId": 2,
      "categoryId": 1,
      "subCategoryId": "4,3,2,1",
      "created": 1738858266,
      "modified": 1738858266,
      "categories": {
        "id": 1,
        "name": "Builders",
        "image": "https://app.superinstajobs.com/uploads/1722582520107.6833.png",
        "status": 1,
        "isSubCategories": 1,
        "created": 0,
        "modified": 1722582520
      },
      "subCategories": [
        {
          "id": 1,
          "categoryId": 1,
          "name": "Bricklayer",
          "image": "",
          "status": 0,
          "created": 0,
          "modified": 0
        }
      ]
    }
  ]
}
*/

  int? id;
  String? name;
  String? email;
  String? phone;
  String? profile;
  int? hourlyPrice;
  int? dailyPrice;
  int? isFav;
  String? overallRating;
  List<CustomerHomeModelDataBoostProfileUserCategories?>? userCategories;

  CustomerHomeModelDataBoostProfile({
    this.id,
    this.name,
    this.email,
    this.phone,
    this.profile,
    this.hourlyPrice,
    this.dailyPrice,
    this.isFav,
    this.overallRating,
    this.userCategories,
  });
  CustomerHomeModelDataBoostProfile.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    email = json['email']?.toString();
    phone = json['phone']?.toString();
    profile = json['profile']?.toString();
    hourlyPrice = json['hourlyPrice']?.toInt();
    dailyPrice = json['dailyPrice']?.toInt();
    isFav = json['isFav']?.toInt();
    overallRating = json['overallRating']?.toString();
    if (json['userCategories'] != null) {
      final v = json['userCategories'];
      final arr0 = <CustomerHomeModelDataBoostProfileUserCategories>[];
      v.forEach((v) {
        arr0.add(CustomerHomeModelDataBoostProfileUserCategories.fromJson(v));
      });
      userCategories = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['email'] = email;
    data['phone'] = phone;
    data['profile'] = profile;
    data['hourlyPrice'] = hourlyPrice;
    data['dailyPrice'] = dailyPrice;
    data['isFav'] = isFav;
    data['overallRating'] = overallRating;
    if (userCategories != null) {
      final v = userCategories;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['userCategories'] = arr0;
    }
    return data;
  }
}

class CustomerHomeModelDataCoupons {
/*
{
  "id": 5,
  "title": "Mega Offer",
  "percentage": 10,
  "image": "https://app.superinstajobs.com/uploads/1732680680099.073.jpeg",
  "code": "INSTA300",
  "couponUseLimit": -1,
  "status": 1,
  "created": 1732680680,
  "modified": 1732773059
}
*/

  int? id;
  String? title;
  int? percentage;
  String? image;
  String? code;
  int? couponUseLimit;
  int? status;
  int? created;
  int? modified;

  CustomerHomeModelDataCoupons({
    this.id,
    this.title,
    this.percentage,
    this.image,
    this.code,
    this.couponUseLimit,
    this.status,
    this.created,
    this.modified,
  });
  CustomerHomeModelDataCoupons.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    title = json['title']?.toString();
    percentage = json['percentage']?.toInt();
    image = json['image']?.toString();
    code = json['code']?.toString();
    couponUseLimit = json['couponUseLimit']?.toInt();
    status = json['status']?.toInt();
    created = json['created']?.toInt();
    modified = json['modified']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['percentage'] = percentage;
    data['image'] = image;
    data['code'] = code;
    data['couponUseLimit'] = couponUseLimit;
    data['status'] = status;
    data['created'] = created;
    data['modified'] = modified;
    return data;
  }
}

class CustomerHomeModelDataViewVendorsReviewsRating {
/*
{
  "reviewsCount": 0,
  "overallRating": "0.0"
}
*/

  int? reviewsCount;
  String? overallRating;

  CustomerHomeModelDataViewVendorsReviewsRating({
    this.reviewsCount,
    this.overallRating,
  });
  CustomerHomeModelDataViewVendorsReviewsRating.fromJson(Map<String, dynamic> json) {
    reviewsCount = json['reviewsCount']?.toInt();
    overallRating = json['overallRating']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['reviewsCount'] = reviewsCount;
    data['overallRating'] = overallRating;
    return data;
  }
}

class CustomerHomeModelDataViewVendorsUsers {
/*
{
  "id": 5,
  "name": "Customer Raj",
  "email": "customerraj@yopmail.com",
  "phone": "7888622222",
  "profile": "https://app.superinstajobs.com/uploads/1738923494025.1042.jpg",
  "hourlyPrice": 0,
  "dailyPrice": 0
}
*/

  int? id;
  String? name;
  String? email;
  String? phone;
  String? profile;
  int? hourlyPrice;
  int? dailyPrice;

  CustomerHomeModelDataViewVendorsUsers({
    this.id,
    this.name,
    this.email,
    this.phone,
    this.profile,
    this.hourlyPrice,
    this.dailyPrice,
  });
  CustomerHomeModelDataViewVendorsUsers.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    email = json['email']?.toString();
    phone = json['phone']?.toString();
    profile = json['profile']?.toString();
    hourlyPrice = json['hourlyPrice']?.toInt();
    dailyPrice = json['dailyPrice']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['email'] = email;
    data['phone'] = phone;
    data['profile'] = profile;
    data['hourlyPrice'] = hourlyPrice;
    data['dailyPrice'] = dailyPrice;
    return data;
  }
}

class CustomerHomeModelDataViewVendors {
/*
{
  "id": 11,
  "venderId": 5,
  "userId": 2,
  "created": 1740077190,
  "modified": 1744212260,
  "users": {
    "id": 5,
    "name": "Customer Raj",
    "email": "customerraj@yopmail.com",
    "phone": "7888622222",
    "profile": "https://app.superinstajobs.com/uploads/1738923494025.1042.jpg",
    "hourlyPrice": 0,
    "dailyPrice": 0
  },
  "reviewsRating": {
    "reviewsCount": 0,
    "overallRating": "0.0"
  },
  "lowestPrice": 0
}
*/

  int? id;
  int? venderId;
  int? userId;
  int? created;
  int? modified;
  CustomerHomeModelDataViewVendorsUsers? users;
  CustomerHomeModelDataViewVendorsReviewsRating? reviewsRating;
  int? lowestPrice;

  CustomerHomeModelDataViewVendors({
    this.id,
    this.venderId,
    this.userId,
    this.created,
    this.modified,
    this.users,
    this.reviewsRating,
    this.lowestPrice,
  });
  CustomerHomeModelDataViewVendors.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    venderId = json['venderId']?.toInt();
    userId = json['userId']?.toInt();
    created = json['created']?.toInt();
    modified = json['modified']?.toInt();
    users = (json['users'] != null) ? CustomerHomeModelDataViewVendorsUsers.fromJson(json['users']) : null;
    reviewsRating = (json['reviewsRating'] != null) ? CustomerHomeModelDataViewVendorsReviewsRating.fromJson(json['reviewsRating']) : null;
    lowestPrice = json['lowestPrice']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['venderId'] = venderId;
    data['userId'] = userId;
    data['created'] = created;
    data['modified'] = modified;
    if (users != null) {
      data['users'] = users!.toJson();
    }
    if (reviewsRating != null) {
      data['reviewsRating'] = reviewsRating!.toJson();
    }
    data['lowestPrice'] = lowestPrice;
    return data;
  }
}

class CustomerHomeModelDataFeatureJobs {
/*
{
  "id": 1,
  "name": "Builders",
  "image": "https://app.superinstajobs.com/uploads/1722582520107.6833.png",
  "status": 1,
  "isSubCategories": 1,
  "created": 0,
  "modified": 1722582520
}
*/

  int? id;
  String? name;
  String? image;
  int? status;
  int? isSubCategories;
  int? created;
  int? modified;

  CustomerHomeModelDataFeatureJobs({
    this.id,
    this.name,
    this.image,
    this.status,
    this.isSubCategories,
    this.created,
    this.modified,
  });
  CustomerHomeModelDataFeatureJobs.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    image = json['image']?.toString();
    status = json['status']?.toInt();
    isSubCategories = json['isSubCategories']?.toInt();
    created = json['created']?.toInt();
    modified = json['modified']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['image'] = image;
    data['status'] = status;
    data['isSubCategories'] = isSubCategories;
    data['created'] = created;
    data['modified'] = modified;
    return data;
  }
}

class CustomerHomeModelDataCategories {
/*
{
  "id": 6,
  "name": "Beauty & Spa",
  "image": "https://app.superinstajobs.com/uploads/1722582563353.6062.png",
  "status": 1,
  "isSubCategories": 0,
  "created": 0,
  "modified": 1722582563
}
*/

  int? id;
  String? name;
  String? image;
  int? status;
  int? isSubCategories;
  int? created;
  int? modified;

  CustomerHomeModelDataCategories({
    this.id,
    this.name,
    this.image,
    this.status,
    this.isSubCategories,
    this.created,
    this.modified,
  });
  CustomerHomeModelDataCategories.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    image = json['image']?.toString();
    status = json['status']?.toInt();
    isSubCategories = json['isSubCategories']?.toInt();
    created = json['created']?.toInt();
    modified = json['modified']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['image'] = image;
    data['status'] = status;
    data['isSubCategories'] = isSubCategories;
    data['created'] = created;
    data['modified'] = modified;
    return data;
  }
}

class CustomerHomeModelData {
/*
{
  "categories": [
    {
      "id": 6,
      "name": "Beauty & Spa",
      "image": "https://app.superinstajobs.com/uploads/1722582563353.6062.png",
      "status": 1,
      "isSubCategories": 0,
      "created": 0,
      "modified": 1722582563
    }
  ],
  "featureJobs": [
    {
      "id": 1,
      "name": "Builders",
      "image": "https://app.superinstajobs.com/uploads/1722582520107.6833.png",
      "status": 1,
      "isSubCategories": 1,
      "created": 0,
      "modified": 1722582520
    }
  ],
  "viewVendors": [
    {
      "id": 11,
      "venderId": 5,
      "userId": 2,
      "created": 1740077190,
      "modified": 1744212260,
      "users": {
        "id": 5,
        "name": "Customer Raj",
        "email": "customerraj@yopmail.com",
        "phone": "7888622222",
        "profile": "https://app.superinstajobs.com/uploads/1738923494025.1042.jpg",
        "hourlyPrice": 0,
        "dailyPrice": 0
      },
      "reviewsRating": {
        "reviewsCount": 0,
        "overallRating": "0.0"
      },
      "lowestPrice": 0
    }
  ],
  "coupons": [
    {
      "id": 5,
      "title": "Mega Offer",
      "percentage": 10,
      "image": "https://app.superinstajobs.com/uploads/1732680680099.073.jpeg",
      "code": "INSTA300",
      "couponUseLimit": -1,
      "status": 1,
      "created": 1732680680,
      "modified": 1732773059
    }
  ],
  "boostProfile": [
    {
      "id": 2,
      "name": "Jyoti Builders",
      "email": "jyoti@yopmail.com",
      "phone": "7888644412",
      "profile": "https://app.superinstajobs.com/uploads/1743437099493.0781.jpg",
      "hourlyPrice": 10,
      "dailyPrice": 100,
      "isFav": 1,
      "overallRating": "0.0",
      "userCategories": [
        {
          "id": 2,
          "userId": 2,
          "categoryId": 1,
          "subCategoryId": "4,3,2,1",
          "created": 1738858266,
          "modified": 1738858266,
          "categories": {
            "id": 1,
            "name": "Builders",
            "image": "https://app.superinstajobs.com/uploads/1722582520107.6833.png",
            "status": 1,
            "isSubCategories": 1,
            "created": 0,
            "modified": 1722582520
          },
          "subCategories": [
            {
              "id": 1,
              "categoryId": 1,
              "name": "Bricklayer",
              "image": "",
              "status": 0,
              "created": 0,
              "modified": 0
            }
          ]
        }
      ]
    }
  ]
}
*/

  List<CustomerHomeModelDataCategories?>? categories;
  List<CustomerHomeModelDataFeatureJobs?>? featureJobs;
  List<CustomerHomeModelDataViewVendors?>? viewVendors;
  List<CustomerHomeModelDataCoupons?>? coupons;
  List<CustomerHomeModelDataBoostProfile?>? boostProfile;

  CustomerHomeModelData({
    this.categories,
    this.featureJobs,
    this.viewVendors,
    this.coupons,
    this.boostProfile,
  });
  CustomerHomeModelData.fromJson(Map<String, dynamic> json) {
    if (json['categories'] != null) {
      final v = json['categories'];
      final arr0 = <CustomerHomeModelDataCategories>[];
      v.forEach((v) {
        arr0.add(CustomerHomeModelDataCategories.fromJson(v));
      });
      categories = arr0;
    }
    if (json['featureJobs'] != null) {
      final v = json['featureJobs'];
      final arr0 = <CustomerHomeModelDataFeatureJobs>[];
      v.forEach((v) {
        arr0.add(CustomerHomeModelDataFeatureJobs.fromJson(v));
      });
      featureJobs = arr0;
    }
    if (json['viewVendors'] != null) {
      final v = json['viewVendors'];
      final arr0 = <CustomerHomeModelDataViewVendors>[];
      v.forEach((v) {
        arr0.add(CustomerHomeModelDataViewVendors.fromJson(v));
      });
      viewVendors = arr0;
    }
    if (json['coupons'] != null) {
      final v = json['coupons'];
      final arr0 = <CustomerHomeModelDataCoupons>[];
      v.forEach((v) {
        arr0.add(CustomerHomeModelDataCoupons.fromJson(v));
      });
      coupons = arr0;
    }
    if (json['boostProfile'] != null) {
      final v = json['boostProfile'];
      final arr0 = <CustomerHomeModelDataBoostProfile>[];
      v.forEach((v) {
        arr0.add(CustomerHomeModelDataBoostProfile.fromJson(v));
      });
      boostProfile = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (categories != null) {
      final v = categories;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['categories'] = arr0;
    }
    if (featureJobs != null) {
      final v = featureJobs;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['featureJobs'] = arr0;
    }
    if (viewVendors != null) {
      final v = viewVendors;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['viewVendors'] = arr0;
    }
    if (coupons != null) {
      final v = coupons;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['coupons'] = arr0;
    }
    if (boostProfile != null) {
      final v = boostProfile;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['boostProfile'] = arr0;
    }
    return data;
  }
}

class CustomerHomeModel {
/*
{
  "success": true,
  "message": "Home listing",
  "status": 200,
  "data": {
    "categories": [
      {
        "id": 6,
        "name": "Beauty & Spa",
        "image": "https://app.superinstajobs.com/uploads/1722582563353.6062.png",
        "status": 1,
        "isSubCategories": 0,
        "created": 0,
        "modified": 1722582563
      }
    ],
    "featureJobs": [
      {
        "id": 1,
        "name": "Builders",
        "image": "https://app.superinstajobs.com/uploads/1722582520107.6833.png",
        "status": 1,
        "isSubCategories": 1,
        "created": 0,
        "modified": 1722582520
      }
    ],
    "viewVendors": [
      {
        "id": 11,
        "venderId": 5,
        "userId": 2,
        "created": 1740077190,
        "modified": 1744212260,
        "users": {
          "id": 5,
          "name": "Customer Raj",
          "email": "customerraj@yopmail.com",
          "phone": "7888622222",
          "profile": "https://app.superinstajobs.com/uploads/1738923494025.1042.jpg",
          "hourlyPrice": 0,
          "dailyPrice": 0
        },
        "reviewsRating": {
          "reviewsCount": 0,
          "overallRating": "0.0"
        },
        "lowestPrice": 0
      }
    ],
    "coupons": [
      {
        "id": 5,
        "title": "Mega Offer",
        "percentage": 10,
        "image": "https://app.superinstajobs.com/uploads/1732680680099.073.jpeg",
        "code": "INSTA300",
        "couponUseLimit": -1,
        "status": 1,
        "created": 1732680680,
        "modified": 1732773059
      }
    ],
    "boostProfile": [
      {
        "id": 2,
        "name": "Jyoti Builders",
        "email": "jyoti@yopmail.com",
        "phone": "7888644412",
        "profile": "https://app.superinstajobs.com/uploads/1743437099493.0781.jpg",
        "hourlyPrice": 10,
        "dailyPrice": 100,
        "isFav": 1,
        "overallRating": "0.0",
        "userCategories": [
          {
            "id": 2,
            "userId": 2,
            "categoryId": 1,
            "subCategoryId": "4,3,2,1",
            "created": 1738858266,
            "modified": 1738858266,
            "categories": {
              "id": 1,
              "name": "Builders",
              "image": "https://app.superinstajobs.com/uploads/1722582520107.6833.png",
              "status": 1,
              "isSubCategories": 1,
              "created": 0,
              "modified": 1722582520
            },
            "subCategories": [
              {
                "id": 1,
                "categoryId": 1,
                "name": "Bricklayer",
                "image": "",
                "status": 0,
                "created": 0,
                "modified": 0
              }
            ]
          }
        ]
      }
    ]
  }
}
*/

  bool? success;
  String? message;
  int? status;
  CustomerHomeModelData? data;

  CustomerHomeModel({
    this.success,
    this.message,
    this.status,
    this.data,
  });
  CustomerHomeModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    status = json['status']?.toInt();
    data = (json['data'] != null) ? CustomerHomeModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    data['status'] = status;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
