///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CategoriesModelDataPagination {
/*
{
  "currentPage": 1,
  "totalPage": 1,
  "totalRecord": 6,
  "limit": 20
}
*/

  int? currentPage;
  int? totalPage;
  int? totalRecord;
  int? limit;

  CategoriesModelDataPagination({
    this.currentPage,
    this.totalPage,
    this.totalRecord,
    this.limit,
  });
  CategoriesModelDataPagination.fromJson(Map<String, dynamic> json) {
    currentPage = json['currentPage']?.toInt();
    totalPage = json['totalPage']?.toInt();
    totalRecord = json['totalRecord']?.toInt();
    limit = json['limit']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['currentPage'] = currentPage;
    data['totalPage'] = totalPage;
    data['totalRecord'] = totalRecord;
    data['limit'] = limit;
    return data;
  }
}

class CategoriesModelDataCategories {
/*
{
  "id": 2,
  "name": "Art Work",
  "image": "https://app.superinstajobs.com/uploads/1722582543205.9453.png",
  "status": 1,
  "isSubCategories": 0,
  "created": 0,
  "modified": 1722582543,
  "totalSubCategories": 1,
  "totalUsers": 0
}
*/

  int? id;
  String? name;
  String? image;
  int? status;
  int? isSubCategories;
  int? created;
  int? modified;
  int? totalSubCategories;
  int? totalUsers;
  bool?isSelected ;

  CategoriesModelDataCategories({
    this.id,
    this.name,
    this.isSelected=false,
    this.image,
    this.status,
    this.isSubCategories,
    this.created,
    this.modified,
    this.totalSubCategories,
    this.totalUsers,
  });
  CategoriesModelDataCategories.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    isSelected = false;
    name = json['name']?.toString();
    image = json['image']?.toString();
    status = json['status']?.toInt();
    isSubCategories = json['isSubCategories']?.toInt();
    created = json['created']?.toInt();
    modified = json['modified']?.toInt();
    totalSubCategories = json['totalSubCategories']?.toInt();
    totalUsers = json['totalUsers']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['isSelected'] = isSelected;

    data['name'] = name;
    data['image'] = image;
    data['status'] = status;
    data['isSubCategories'] = isSubCategories;
    data['created'] = created;
    data['modified'] = modified;
    data['totalSubCategories'] = totalSubCategories;
    data['totalUsers'] = totalUsers;
    return data;
  }
}

class CategoriesModelData {
/*
{
  "categories": [
    {
      "id": 2,
      "name": "Art Work",
      "image": "https://app.superinstajobs.com/uploads/1722582543205.9453.png",
      "status": 1,
      "isSubCategories": 0,
      "created": 0,
      "modified": 1722582543,
      "totalSubCategories": 1,
      "totalUsers": 0
    }
  ],
  "pagination": {
    "currentPage": 1,
    "totalPage": 1,
    "totalRecord": 6,
    "limit": 20
  }
}
*/

  List<CategoriesModelDataCategories?>? categories;
  CategoriesModelDataPagination? pagination;

  CategoriesModelData({
    this.categories,
    this.pagination,
  });
  CategoriesModelData.fromJson(Map<String, dynamic> json) {
    if (json['categories'] != null) {
      final v = json['categories'];
      final arr0 = <CategoriesModelDataCategories>[];
      v.forEach((v) {
        arr0.add(CategoriesModelDataCategories.fromJson(v));
      });
      categories = arr0;
    }
    pagination = (json['pagination'] != null) ? CategoriesModelDataPagination.fromJson(json['pagination']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (categories != null) {
      final v = categories;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['categories'] = arr0;
    }
    if (pagination != null) {
      data['pagination'] = pagination!.toJson();
    }
    return data;
  }
}

class CategoriesModel {
/*
{
  "success": true,
  "message": "Category listing",
  "status": 200,
  "data": {
    "categories": [
      {
        "id": 2,
        "name": "Art Work",
        "image": "https://app.superinstajobs.com/uploads/1722582543205.9453.png",
        "status": 1,
        "isSubCategories": 0,
        "created": 0,
        "modified": 1722582543,
        "totalSubCategories": 1,
        "totalUsers": 0
      }
    ],
    "pagination": {
      "currentPage": 1,
      "totalPage": 1,
      "totalRecord": 6,
      "limit": 20
    }
  }
}
*/

  bool? success;
  String? message;
  int? status;
  CategoriesModelData? data;

  CategoriesModel({
    this.success,
    this.message,
    this.status,
    this.data,
  });
  CategoriesModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    status = json['status']?.toInt();
    data = (json['data'] != null) ? CategoriesModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    data['status'] = status;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
