///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ChangePasswordModel {
/*
{
  "success": true,
  "message": "Password changed successfully",
  "status": 200
}
*/

  bool? success;
  String? message;
  int? status;

  ChangePasswordModel({
    this.success,
    this.message,
    this.status,
  });
  ChangePasswordModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    status = json['status']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    data['status'] = status;
    return data;
  }
}
