///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class FavFreelancersModelDataPagination {
/*
{
  "currentPage": 1,
  "totalPage": 1,
  "totalRecord": 3,
  "limit": 20
}
*/

  int? currentPage;
  int? totalPage;
  int? totalRecord;
  int? limit;

  FavFreelancersModelDataPagination({
    this.currentPage,
    this.totalPage,
    this.totalRecord,
    this.limit,
  });
  FavFreelancersModelDataPagination.fromJson(Map<String, dynamic> json) {
    currentPage = json['currentPage']?.toInt();
    totalPage = json['totalPage']?.toInt();
    totalRecord = json['totalRecord']?.toInt();
    limit = json['limit']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['currentPage'] = currentPage;
    data['totalPage'] = totalPage;
    data['totalRecord'] = totalRecord;
    data['limit'] = limit;
    return data;
  }
}

class FavFreelancersModelDataDataVendors {
/*
{
  "id": 16,
  "name": "sonal",
  "email": "xyz@gmail.com",
  "phone": "90909090",
  "profile": "",
  "userTypes": 1,
  "descriptions": "1212121",
  "totalJobs": 0,
  "totalHours": 0,
  "totalEarning": 0,
  "status": 0,
  "country": "tt",
  "state": "t",
  "city": "t",
  "street": "t",
  "latitude": 30.3456,
  "longitude": 74.23232,
  "boostTime": 0,
  "isBoosted": 0,
  "hourlyPrice": 0,
  "dailyPrice": 0,
  "favVendor": 1,
  "reviewsCount": 0,
  "lowestPrice": 0,
  "overallRating": "0.0"
}
*/

  int? id;
  String? name;
  String? email;
  String? phone;
  String? profile;
  int? userTypes;
  String? descriptions;
  int? totalJobs;
  int? totalHours;
  int? totalEarning;
  int? status;
  String? country;
  String? state;
  String? city;
  String? street;
  double? latitude;
  double? longitude;
  int? boostTime;
  int? isBoosted;
  int? hourlyPrice;
  int? dailyPrice;
  int? favVendor;
  int? reviewsCount;
  int? lowestPrice;
  String? overallRating;

  FavFreelancersModelDataDataVendors({
    this.id,
    this.name,
    this.email,
    this.phone,
    this.profile,
    this.userTypes,
    this.descriptions,
    this.totalJobs,
    this.totalHours,
    this.totalEarning,
    this.status,
    this.country,
    this.state,
    this.city,
    this.street,
    this.latitude,
    this.longitude,
    this.boostTime,
    this.isBoosted,
    this.hourlyPrice,
    this.dailyPrice,
    this.favVendor,
    this.reviewsCount,
    this.lowestPrice,
    this.overallRating,
  });
  FavFreelancersModelDataDataVendors.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    email = json['email']?.toString();
    phone = json['phone']?.toString();
    profile = json['profile']?.toString();
    userTypes = json['userTypes']?.toInt();
    descriptions = json['descriptions']?.toString();
    totalJobs = json['totalJobs']?.toInt();
    totalHours = json['totalHours']?.toInt();
    totalEarning = json['totalEarning']?.toInt();
    status = json['status']?.toInt();
    country = json['country']?.toString();
    state = json['state']?.toString();
    city = json['city']?.toString();
    street = json['street']?.toString();
    latitude = json['latitude']?.toDouble();
    longitude = json['longitude']?.toDouble();
    boostTime = json['boostTime']?.toInt();
    isBoosted = json['isBoosted']?.toInt();
    hourlyPrice = json['hourlyPrice']?.toInt();
    dailyPrice = json['dailyPrice']?.toInt();
    favVendor = json['favVendor']?.toInt();
    reviewsCount = json['reviewsCount']?.toInt();
    lowestPrice = json['lowestPrice']?.toInt();
    overallRating = json['overallRating']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['email'] = email;
    data['phone'] = phone;
    data['profile'] = profile;
    data['userTypes'] = userTypes;
    data['descriptions'] = descriptions;
    data['totalJobs'] = totalJobs;
    data['totalHours'] = totalHours;
    data['totalEarning'] = totalEarning;
    data['status'] = status;
    data['country'] = country;
    data['state'] = state;
    data['city'] = city;
    data['street'] = street;
    data['latitude'] = latitude;
    data['longitude'] = longitude;
    data['boostTime'] = boostTime;
    data['isBoosted'] = isBoosted;
    data['hourlyPrice'] = hourlyPrice;
    data['dailyPrice'] = dailyPrice;
    data['favVendor'] = favVendor;
    data['reviewsCount'] = reviewsCount;
    data['lowestPrice'] = lowestPrice;
    data['overallRating'] = overallRating;
    return data;
  }
}

class FavFreelancersModelDataData {
/*
{
  "id": 3,
  "userId": 2,
  "vendorId": 16,
  "created": 1747243930,
  "modified": 1747243930,
  "vendors": {
    "id": 16,
    "name": "sonal",
    "email": "xyz@gmail.com",
    "phone": "90909090",
    "profile": "",
    "userTypes": 1,
    "descriptions": "1212121",
    "totalJobs": 0,
    "totalHours": 0,
    "totalEarning": 0,
    "status": 0,
    "country": "tt",
    "state": "t",
    "city": "t",
    "street": "t",
    "latitude": 30.3456,
    "longitude": 74.23232,
    "boostTime": 0,
    "isBoosted": 0,
    "hourlyPrice": 0,
    "dailyPrice": 0,
    "favVendor": 1,
    "reviewsCount": 0,
    "lowestPrice": 0,
    "overallRating": "0.0"
  }
}
*/

  int? id;
  int? userId;
  int? vendorId;
  int? created;
  int? modified;
  FavFreelancersModelDataDataVendors? vendors;

  FavFreelancersModelDataData({
    this.id,
    this.userId,
    this.vendorId,
    this.created,
    this.modified,
    this.vendors,
  });
  FavFreelancersModelDataData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    userId = json['userId']?.toInt();
    vendorId = json['vendorId']?.toInt();
    created = json['created']?.toInt();
    modified = json['modified']?.toInt();
    vendors = (json['vendors'] != null) ? FavFreelancersModelDataDataVendors.fromJson(json['vendors']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['userId'] = userId;
    data['vendorId'] = vendorId;
    data['created'] = created;
    data['modified'] = modified;
    if (vendors != null) {
      data['vendors'] = vendors!.toJson();
    }
    return data;
  }
}

class FavFreelancersModelData {
/*
{
  "data": [
    {
      "id": 3,
      "userId": 2,
      "vendorId": 16,
      "created": 1747243930,
      "modified": 1747243930,
      "vendors": {
        "id": 16,
        "name": "sonal",
        "email": "xyz@gmail.com",
        "phone": "90909090",
        "profile": "",
        "userTypes": 1,
        "descriptions": "1212121",
        "totalJobs": 0,
        "totalHours": 0,
        "totalEarning": 0,
        "status": 0,
        "country": "tt",
        "state": "t",
        "city": "t",
        "street": "t",
        "latitude": 30.3456,
        "longitude": 74.23232,
        "boostTime": 0,
        "isBoosted": 0,
        "hourlyPrice": 0,
        "dailyPrice": 0,
        "favVendor": 1,
        "reviewsCount": 0,
        "lowestPrice": 0,
        "overallRating": "0.0"
      }
    }
  ],
  "pagination": {
    "currentPage": 1,
    "totalPage": 1,
    "totalRecord": 3,
    "limit": 20
  }
}
*/

  List<FavFreelancersModelDataData?>? data;
  FavFreelancersModelDataPagination? pagination;

  FavFreelancersModelData({
    this.data,
    this.pagination,
  });
  FavFreelancersModelData.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <FavFreelancersModelDataData>[];
      v.forEach((v) {
        arr0.add(FavFreelancersModelDataData.fromJson(v));
      });
      this.data = arr0;
    }
    pagination = (json['pagination'] != null) ? FavFreelancersModelDataPagination.fromJson(json['pagination']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    if (pagination != null) {
      data['pagination'] = pagination!.toJson();
    }
    return data;
  }
}

class FavFreelancersModel {
/*
{
  "success": true,
  "message": "Fav vendor list",
  "status": 200,
  "data": {
    "data": [
      {
        "id": 3,
        "userId": 2,
        "vendorId": 16,
        "created": 1747243930,
        "modified": 1747243930,
        "vendors": {
          "id": 16,
          "name": "sonal",
          "email": "xyz@gmail.com",
          "phone": "90909090",
          "profile": "",
          "userTypes": 1,
          "descriptions": "1212121",
          "totalJobs": 0,
          "totalHours": 0,
          "totalEarning": 0,
          "status": 0,
          "country": "tt",
          "state": "t",
          "city": "t",
          "street": "t",
          "latitude": 30.3456,
          "longitude": 74.23232,
          "boostTime": 0,
          "isBoosted": 0,
          "hourlyPrice": 0,
          "dailyPrice": 0,
          "favVendor": 1,
          "reviewsCount": 0,
          "lowestPrice": 0,
          "overallRating": "0.0"
        }
      }
    ],
    "pagination": {
      "currentPage": 1,
      "totalPage": 1,
      "totalRecord": 3,
      "limit": 20
    }
  }
}
*/

  bool? success;
  String? message;
  int? status;
  FavFreelancersModelData? data;

  FavFreelancersModel({
    this.success,
    this.message,
    this.status,
    this.data,
  });
  FavFreelancersModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    status = json['status']?.toInt();
    data = (json['data'] != null) ? FavFreelancersModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    data['status'] = status;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
