///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ForgotPassModelData {
/*
{
  "forgotPasswordToken": "2e8516d23055e6fabf15fd92d9636258941d1b60"
}
*/

  String? forgotPasswordToken;

  ForgotPassModelData({
    this.forgotPasswordToken,
  });
  ForgotPassModelData.fromJson(Map<String, dynamic> json) {
    forgotPasswordToken = json['forgotPasswordToken']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['forgotPasswordToken'] = forgotPasswordToken;
    return data;
  }
}

class ForgotPassModel {
/*
{
  "success": true,
  "message": "OTP has been sent to your registered mobile number",
  "status": 200,
  "data": {
    "forgotPasswordToken": "2e8516d23055e6fabf15fd92d9636258941d1b60"
  }
}
*/

  bool? success;
  String? message;
  int? status;
  ForgotPassModelData? data;

  ForgotPassModel({
    this.success,
    this.message,
    this.status,
    this.data,
  });
  ForgotPassModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    status = json['status']?.toInt();

    if (json['data'] != null && json['data'] is Map<String, dynamic>) {
      data = ForgotPassModelData.fromJson(json['data']);
    } else {
      data = null; // in case it's int, string, or null
    }
    // data = (json['data'] != null) ? ForgotPassModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    data['status'] = status;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}


class OfferPurchaseResponse {
  final bool success;
  final String message;
  final int status;
  final OfferData? data;

  OfferPurchaseResponse({
    required this.success,
    required this.message,
    required this.status,
    this.data,
  });

  factory OfferPurchaseResponse.fromJson(Map<String, dynamic> json) {
    return OfferPurchaseResponse(
      success: json['success'] ?? false,
      message: json['message'] ?? '',
      status: json['status'] ?? 0,
      data: json['data'] != null ? OfferData.fromJson(json['data']) : null,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      "success": success,
      "message": message,
      "status": status,
      "data": data?.toJson(),
    };
  }
}

class OfferData {
  final int id;

  OfferData({required this.id});

  factory OfferData.fromJson(Map<String, dynamic> json) {
    return OfferData(
      id: json['id'] ?? 0,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      "id": id,
    };
  }
}
