///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ForgotPassModelData {
/*
{
  "forgotPasswordToken": "2e8516d23055e6fabf15fd92d9636258941d1b60"
}
*/

  String? forgotPasswordToken;

  ForgotPassModelData({
    this.forgotPasswordToken,
  });
  ForgotPassModelData.fromJson(Map<String, dynamic> json) {
    forgotPasswordToken = json['forgotPasswordToken']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['forgotPasswordToken'] = forgotPasswordToken;
    return data;
  }
}

class ForgotPassModel {
/*
{
  "success": true,
  "message": "OTP has been sent to your registered mobile number",
  "status": 200,
  "data": {
    "forgotPasswordToken": "2e8516d23055e6fabf15fd92d9636258941d1b60"
  }
}
*/

  bool? success;
  String? message;
  int? status;
  ForgotPassModelData? data;

  ForgotPassModel({
    this.success,
    this.message,
    this.status,
    this.data,
  });
  ForgotPassModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    status = json['status']?.toInt();
    data = (json['data'] != null) ? ForgotPassModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    data['status'] = status;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
