///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LinkBankAccountModelData {
/*
{
  "fieldCount": 0,
  "affectedRows": 1,
  "insertId": 2,
  "info": "",
  "serverStatus": 2,
  "warningStatus": 0,
  "changedRows": 0
}
*/

  int? fieldCount;
  int? affectedRows;
  int? insertId;
  String? info;
  int? serverStatus;
  int? warningStatus;
  int? changedRows;

  LinkBankAccountModelData({
    this.fieldCount,
    this.affectedRows,
    this.insertId,
    this.info,
    this.serverStatus,
    this.warningStatus,
    this.changedRows,
  });
  LinkBankAccountModelData.fromJson(Map<String, dynamic> json) {
    fieldCount = json['fieldCount']?.toInt();
    affectedRows = json['affectedRows']?.toInt();
    insertId = json['insertId']?.toInt();
    info = json['info']?.toString();
    serverStatus = json['serverStatus']?.toInt();
    warningStatus = json['warningStatus']?.toInt();
    changedRows = json['changedRows']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['fieldCount'] = fieldCount;
    data['affectedRows'] = affectedRows;
    data['insertId'] = insertId;
    data['info'] = info;
    data['serverStatus'] = serverStatus;
    data['warningStatus'] = warningStatus;
    data['changedRows'] = changedRows;
    return data;
  }
}

class LinkBankAccountModel {
/*
{
  "success": true,
  "message": "Bank account linked successfully",
  "status": 200,
  "data": {
    "fieldCount": 0,
    "affectedRows": 1,
    "insertId": 2,
    "info": "",
    "serverStatus": 2,
    "warningStatus": 0,
    "changedRows": 0
  }
}
*/

  bool? success;
  String? message;
  int? status;
  LinkBankAccountModelData? data;

  LinkBankAccountModel({
    this.success,
    this.message,
    this.status,
    this.data,
  });
  LinkBankAccountModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    status = json['status']?.toInt();
    data = (json['data'] != null) ? LinkBankAccountModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    data['status'] = status;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
