///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MyBookingModelDataPagination {
/*
{
  "currentPage": 1,
  "totalPage": 1,
  "totalRecord": 1,
  "limit": 20
}
*/

  int? currentPage;
  int? totalPage;
  int? totalRecord;
  int? limit;

  MyBookingModelDataPagination({
    this.currentPage,
    this.totalPage,
    this.totalRecord,
    this.limit,
  });
  MyBookingModelDataPagination.fromJson(Map<String, dynamic> json) {
    currentPage = json['currentPage']?.toInt();
    totalPage = json['totalPage']?.toInt();
    totalRecord = json['totalRecord']?.toInt();
    limit = json['limit']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['currentPage'] = currentPage;
    data['totalPage'] = totalPage;
    data['totalRecord'] = totalRecord;
    data['limit'] = limit;
    return data;
  }
}

class MyBookingModelDataDataUsers {
/*
{
  "id": 2,
  "name": "Jyoti Builders",
  "email": "jyoti@yopmail.com",
  "phone": "7888644412",
  "profile": "https://app.superinstajobs.com/uploads/1743437099493.0781.jpg",
  "hourlyPrice": 10,
  "dailyPrice": 100,
  "categoryName": "Builders"
}
*/

  int? id;
  String? name;
  String? email;
  String? phone;
  String? profile;
  int? hourlyPrice;
  int? dailyPrice;
  String? categoryName;

  MyBookingModelDataDataUsers({
    this.id,
    this.name,
    this.email,
    this.phone,
    this.profile,
    this.hourlyPrice,
    this.dailyPrice,
    this.categoryName,
  });
  MyBookingModelDataDataUsers.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    email = json['email']?.toString();
    phone = json['phone']?.toString();
    profile = json['profile']?.toString();
    hourlyPrice = json['hourlyPrice']?.toInt();
    dailyPrice = json['dailyPrice']?.toInt();
    categoryName = json['categoryName']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['email'] = email;
    data['phone'] = phone;
    data['profile'] = profile;
    data['hourlyPrice'] = hourlyPrice;
    data['dailyPrice'] = dailyPrice;
    data['categoryName'] = categoryName;
    return data;
  }
}

class MyBookingModelDataDataSubCategories {
/*
{
  "id": 2,
  "categoryId": 1,
  "name": "Tiler",
  "image": "",
  "status": 0,
  "created": 0,
  "modified": 0
}
*/

  int? id;
  int? categoryId;
  String? name;
  String? image;
  int? status;
  int? created;
  int? modified;

  MyBookingModelDataDataSubCategories({
    this.id,
    this.categoryId,
    this.name,
    this.image,
    this.status,
    this.created,
    this.modified,
  });
  MyBookingModelDataDataSubCategories.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    categoryId = json['categoryId']?.toInt();
    name = json['name']?.toString();
    image = json['image']?.toString();
    status = json['status']?.toInt();
    created = json['created']?.toInt();
    modified = json['modified']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['categoryId'] = categoryId;
    data['name'] = name;
    data['image'] = image;
    data['status'] = status;
    data['created'] = created;
    data['modified'] = modified;
    return data;
  }
}

class MyBookingModelDataDataFreelancer {
/*
{
  "id": 6,
  "name": "Dave",
  "email": "davi.geologist@gmail.com",
  "phone": "123456789",
  "profile": "https://app.superinstajobs.com/uploads/1739114526295.5203.jpg",
  "hourlyPrice": 0,
  "dailyPrice": 0,
  "country": "Nigeria",
  "state": "Lagos",
  "city": "Lagos",
  "street": "Fola Agoro Street, 5, null",
  "categoryName": ""
}
*/

  int? id;
  String? name;
  String? email;
  String? phone;
  String? profile;
  int? hourlyPrice;
  int? dailyPrice;
  String? country;
  String? state;
  String? city;
  String? street;
  String? categoryName;

  MyBookingModelDataDataFreelancer({
    this.id,
    this.name,
    this.email,
    this.phone,
    this.profile,
    this.hourlyPrice,
    this.dailyPrice,
    this.country,
    this.state,
    this.city,
    this.street,
    this.categoryName,
  });
  MyBookingModelDataDataFreelancer.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    email = json['email']?.toString();
    phone = json['phone']?.toString();
    profile = json['profile']?.toString();
    hourlyPrice = json['hourlyPrice']?.toInt();
    dailyPrice = json['dailyPrice']?.toInt();
    country = json['country']?.toString();
    state = json['state']?.toString();
    city = json['city']?.toString();
    street = json['street']?.toString();
    categoryName = json['categoryName']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['email'] = email;
    data['phone'] = phone;
    data['profile'] = profile;
    data['hourlyPrice'] = hourlyPrice;
    data['dailyPrice'] = dailyPrice;
    data['country'] = country;
    data['state'] = state;
    data['city'] = city;
    data['street'] = street;
    data['categoryName'] = categoryName;
    return data;
  }
}

class MyBookingModelDataData {


  int? id;
  int? userId;
  int? date;
  String? time;
  String? endTime;
  int? endDate;
  String? recipientName;
  String? address;
  String? postalCode;
  double? latitude;
  double? longitude;
  String? phone;
  int? assignUserId;
  int? status;
  int? paymentStatus;
  int? price;
  int? bookingType;
  String? notes;
  String? subCategoryIds;
  int? created;
  int? modified;
  int? isRated;
  List<AddOnModel>? addOns;
  MyBookingModelDataDataFreelancer? freelancer;
  List<MyBookingModelDataDataSubCategories?>? subCategories;
  MyBookingModelDataDataUsers? users;

  MyBookingModelDataData({
    this.id,
    this.userId,
    this.date,
    this.time,
    this.endTime,
    this.endDate,
    this.recipientName,
    this.address,
    this.postalCode,
    this.latitude,
    this.longitude,
    this.phone,
    this.assignUserId,
    this.status,
    this.paymentStatus,
    this.price,
    this.bookingType,
    this.notes,
    this.subCategoryIds,
    this.created,
    this.modified,
    this.isRated,
    this.addOns,
    this.freelancer,
    this.subCategories,
    this.users,
  });
  MyBookingModelDataData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    userId = json['userId']?.toInt();
    date = json['date']?.toInt();
    time = json['time']?.toString();
    endTime = json['endTime']?.toString();
    endDate = json['endDate']?.toInt();
    recipientName = json['recipientName']?.toString();
    address = json['address']?.toString();
    postalCode = json['postalCode']?.toString();
    latitude = json['latitude']?.toDouble();
    longitude = json['longitude']?.toDouble();
    phone = json['phone']?.toString();
    assignUserId = json['assignUserId']?.toInt();
    status = json['status']?.toInt();
    paymentStatus = json['paymentStatus']?.toInt();
    price = json['price']?.toInt();
    bookingType = json['bookingType']?.toInt();
    notes = json['notes']?.toString();
    subCategoryIds = json['subCategoryIds']?.toString();
    created = json['created']?.toInt();
    modified = json['modified']?.toInt();
    if (json['isRated'] is int) {
      isRated = json['isRated'];
    } else if (json['isRated'] is bool) {
      isRated = json['isRated'] ? 1 : 0;
    } else {
      isRated = null;
    }
    // if (json['addOns'] != null) {
    //   final v = json['addOns'];
    //   final arr0 = <String>[];
    //   v.forEach((v) {
    //     arr0.add(v.toString());
    //   });
    //   addOns = arr0;
    // }

    if (json['addOns'] != null) {
      final v = json['addOns'] as List;
      addOns = v.map((e) => AddOnModel.fromJson(e)).toList();
    }
    freelancer = (json['freelancer'] != null) ? MyBookingModelDataDataFreelancer.fromJson(json['freelancer']) : null;
    if (json['subCategories'] != null) {
      final v = json['subCategories'];
      final arr0 = <MyBookingModelDataDataSubCategories>[];
      v.forEach((v) {
        arr0.add(MyBookingModelDataDataSubCategories.fromJson(v));
      });
      subCategories = arr0;
    }
    users = (json['users'] != null) ? MyBookingModelDataDataUsers.fromJson(json['users']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['userId'] = userId;
    data['date'] = date;
    data['time'] = time;
    data['endTime'] = endTime;
    data['endDate'] = endDate;
    data['recipientName'] = recipientName;
    data['address'] = address;
    data['postalCode'] = postalCode;
    data['latitude'] = latitude;
    data['longitude'] = longitude;
    data['phone'] = phone;
    data['assignUserId'] = assignUserId;
    data['status'] = status;
    data['paymentStatus'] = paymentStatus;
    data['price'] = price;
    data['bookingType'] = bookingType;
    data['notes'] = notes;
    data['subCategoryIds'] = subCategoryIds;
    data['created'] = created;
    data['modified'] = modified;
    data['isRated'] = isRated;

    if (addOns != null) {
      data['addOns'] = addOns!.map((e) => e.toJson()).toList();
    }
    // if (addOns != null) {
    //   final v = addOns;
    //   final arr0 = [];
    //   v!.forEach((v) {
    //     arr0.add(v);
    //   });
    //   data['addOns'] = arr0;
    // }
    if (freelancer != null) {
      data['freelancer'] = freelancer!.toJson();
    }
    if (subCategories != null) {
      final v = subCategories;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['subCategories'] = arr0;
    }
    if (users != null) {
      data['users'] = users!.toJson();
    }
    return data;
  }
}

class MyBookingModelData {
/*
{
  "data": [
    {
      "id": 4,
      "userId": 2,
      "date": 1736961035,
      "time": "10:12:00",
      "endTime": "12:30:00",
      "endDate": 1736961035,
      "recipientName": "Game name",
      "address": "UNA",
      "postalCode": "174306",
      "latitude": 30.7269755,
      "longitude": 76.8441849,
      "phone": "8894041118",
      "assignUserId": 6,
      "status": 0,
      "paymentStatus": 0,
      "price": 290,
      "bookingType": 1,
      "notes": "Noted is here",
      "subCategoryIds": "4,3,2",
      "created": 1739897407,
      "modified": 1739897407,
      "isRated": 0,
      "addOns": [
        ""
      ],
      "freelancer": {
        "id": 6,
        "name": "Dave",
        "email": "davi.geologist@gmail.com",
        "phone": "123456789",
        "profile": "https://app.superinstajobs.com/uploads/1739114526295.5203.jpg",
        "hourlyPrice": 0,
        "dailyPrice": 0,
        "country": "Nigeria",
        "state": "Lagos",
        "city": "Lagos",
        "street": "Fola Agoro Street, 5, null",
        "categoryName": ""
      },
      "subCategories": [
        {
          "id": 2,
          "categoryId": 1,
          "name": "Tiler",
          "image": "",
          "status": 0,
          "created": 0,
          "modified": 0
        }
      ],
      "users": {
        "id": 2,
        "name": "Jyoti Builders",
        "email": "jyoti@yopmail.com",
        "phone": "7888644412",
        "profile": "https://app.superinstajobs.com/uploads/1743437099493.0781.jpg",
        "hourlyPrice": 10,
        "dailyPrice": 100,
        "categoryName": "Builders"
      }
    }
  ],
  "pagination": {
    "currentPage": 1,
    "totalPage": 1,
    "totalRecord": 1,
    "limit": 20
  }
}
*/

  List<MyBookingModelDataData?>? data;
  MyBookingModelDataPagination? pagination;

  MyBookingModelData({
    this.data,
    this.pagination,
  });
  MyBookingModelData.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <MyBookingModelDataData>[];
      v.forEach((v) {
        arr0.add(MyBookingModelDataData.fromJson(v));
      });
      this.data = arr0;
    }
    pagination = (json['pagination'] != null) ? MyBookingModelDataPagination.fromJson(json['pagination']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    if (pagination != null) {
      data['pagination'] = pagination!.toJson();
    }
    return data;
  }
}

class MyBookingModel {
/*
{
  "success": true,
  "message": "Booking List",
  "status": 200,
  "data": {
    "data": [
      {
        "id": 4,
        "userId": 2,
        "date": 1736961035,
        "time": "10:12:00",
        "endTime": "12:30:00",
        "endDate": 1736961035,
        "recipientName": "Game name",
        "address": "UNA",
        "postalCode": "174306",
        "latitude": 30.7269755,
        "longitude": 76.8441849,
        "phone": "8894041118",
        "assignUserId": 6,
        "status": 0,
        "paymentStatus": 0,
        "price": 290,
        "bookingType": 1,
        "notes": "Noted is here",
        "subCategoryIds": "4,3,2",
        "created": 1739897407,
        "modified": 1739897407,
        "isRated": 0,
        "addOns": [
          ""
        ],
        "freelancer": {
          "id": 6,
          "name": "Dave",
          "email": "davi.geologist@gmail.com",
          "phone": "123456789",
          "profile": "https://app.superinstajobs.com/uploads/1739114526295.5203.jpg",
          "hourlyPrice": 0,
          "dailyPrice": 0,
          "country": "Nigeria",
          "state": "Lagos",
          "city": "Lagos",
          "street": "Fola Agoro Street, 5, null",
          "categoryName": ""
        },
        "subCategories": [
          {
            "id": 2,
            "categoryId": 1,
            "name": "Tiler",
            "image": "",
            "status": 0,
            "created": 0,
            "modified": 0
          }
        ],
        "users": {
          "id": 2,
          "name": "Jyoti Builders",
          "email": "jyoti@yopmail.com",
          "phone": "7888644412",
          "profile": "https://app.superinstajobs.com/uploads/1743437099493.0781.jpg",
          "hourlyPrice": 10,
          "dailyPrice": 100,
          "categoryName": "Builders"
        }
      }
    ],
    "pagination": {
      "currentPage": 1,
      "totalPage": 1,
      "totalRecord": 1,
      "limit": 20
    }
  }
}
*/

  bool? success;
  String? message;
  int? status;
  MyBookingModelData? data;

  MyBookingModel({
    this.success,
    this.message,
    this.status,
    this.data,
  });
  MyBookingModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    status = json['status']?.toInt();
    data = (json['data'] != null) ? MyBookingModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    data['status'] = status;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}


class MyBookingDetailModel {


  bool? success;
  String? message;
  int? status;
  MyBookingModelDataData? data;

  MyBookingDetailModel({
    this.success,
    this.message,
    this.status,
    this.data,
  });
  MyBookingDetailModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    status = json['status'];
    data = (json['data'] != null) ? MyBookingModelDataData.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final jsonData = <String, dynamic>{};
    jsonData['success'] = success;
    jsonData['message'] = message;
    jsonData['status'] = status;

    if (this.data != null) {
      jsonData['data'] = this.data!.toJson();
    }
    return jsonData;
  }
}

class AddOnModel {
  int? id;
  int? userId;
  int? bookingId;
  int? price;
  String? description;
  int? status;
  int? timeToComplete;
  int? paymentStatus;
  int? created;
  int? modified;

  AddOnModel({
    this.id,
    this.userId,
    this.bookingId,
    this.price,
    this.description,
    this.status,
    this.timeToComplete,
    this.paymentStatus,
    this.created,
    this.modified,
  });

  factory AddOnModel.fromJson(Map<String, dynamic> json) {
    return AddOnModel(
      id: json['id']?.toInt(),
      userId: json['userId']?.toInt(),
      bookingId: json['bookingId']?.toInt(),
      price: json['price']?.toInt(),
      description: json['description']?.toString(),
      status: json['status']?.toInt(),
      timeToComplete: json['timeToComplete']?.toInt(),
      paymentStatus: json['paymentStatus']?.toInt(),
      created: json['created']?.toInt(),
      modified: json['modified']?.toInt(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'userId': userId,
      'bookingId': bookingId,
      'price': price,
      'description': description,
      'status': status,
      'timeToComplete': timeToComplete,
      'paymentStatus': paymentStatus,
      'created': created,
      'modified': modified,
    };
  }
}