///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MyInstaJobsModelDataPagination {
/*
{
  "currentPage": 1,
  "totalPage": 1,
  "totalRecord": 1,
  "limit": 8
}
*/

  int? currentPage;
  int? totalPage;
  int? totalRecord;
  int? limit;

  MyInstaJobsModelDataPagination({
    this.currentPage,
    this.totalPage,
    this.totalRecord,
    this.limit,
  });
  MyInstaJobsModelDataPagination.fromJson(Map<String, dynamic> json) {
    currentPage = json['currentPage']?.toInt();
    totalPage = json['totalPage']?.toInt();
    totalRecord = json['totalRecord']?.toInt();
    limit = json['limit']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['currentPage'] = currentPage;
    data['totalPage'] = totalPage;
    data['totalRecord'] = totalRecord;
    data['limit'] = limit;
    return data;
  }
}

class MyInstaJobsModelDataDataCategories {
/*
{
  "id": 1,
  "name": "Builders",
  "image": "https://app.superinstajobs.com/uploads/1722582520107.6833.png",
  "status": 1,
  "isSubCategories": 1,
  "created": 0,
  "modified": 1722582520
}
*/

  int? id;
  String? name;
  String? image;
  int? status;
  int? isSubCategories;
  int? created;
  int? modified;

  MyInstaJobsModelDataDataCategories({
    this.id,
    this.name,
    this.image,
    this.status,
    this.isSubCategories,
    this.created,
    this.modified,
  });
  MyInstaJobsModelDataDataCategories.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    image = json['image']?.toString();
    status = json['status']?.toInt();
    isSubCategories = json['isSubCategories']?.toInt();
    created = json['created']?.toInt();
    modified = json['modified']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['image'] = image;
    data['status'] = status;
    data['isSubCategories'] = isSubCategories;
    data['created'] = created;
    data['modified'] = modified;
    return data;
  }
}

class MyInstaJobsModelDataDataUsers {
/*
{
  "id": 4,
  "name": "Jyoti",
  "email": "jyoti@gmail.com",
  "phone": "8074693258",
  "profile": "https://app.superinstajobs.com/uploads/1738859793805.6748.jpg"
}
*/

  int? id;
  String? name;
  String? email;
  String? phone;
  String? profile;

  MyInstaJobsModelDataDataUsers({
    this.id,
    this.name,
    this.email,
    this.phone,
    this.profile,
  });
  MyInstaJobsModelDataDataUsers.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    email = json['email']?.toString();
    phone = json['phone']?.toString();
    profile = json['profile']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['email'] = email;
    data['phone'] = phone;
    data['profile'] = profile;
    return data;
  }
}

class MyInstaJobsModelDataData {
/*
{
  "id": 1,
  "userId": 4,
  "title": "Need a Plumber for Tap fixing",
  "categoryId": 1,
  "subCategoryId": 3,
  "devilryTime": 1,
  "isJobEnd": 0,
  "country": "",
  "state": "",
  "latitude": 0,
  "longitude": 0,
  "descriptions": "Need a plumber to fix me bathroom tap urgently.",
  "assignUserId": 0,
  "locations": "",
  "totalBudgets": 500,
  "isRaiseDispute": 0,
  "attachments": "https://app.superinstajobs.com/uploads/1738862433368.4587.jpg",
  "defaultVideoLink": "",
  "acceptedBudget": 0,
  "isAssigned": 0,
  "isFeature": 0,
  "isAnyWhere": 1,
  "skills": "Plumber",
  "priceForm": 400,
  "priceTo": 400,
  "experience": "Expert",
  "isBoosted": 0,
  "boostTime": 0,
  "disputeId": 0,
  "created": 1738862433,
  "modified": 1738862433,
  "isFav": 0,
  "totalProposals": 1,
  "isSendProposals": 1,
  "users": {
    "id": 4,
    "name": "Jyoti",
    "email": "jyoti@gmail.com",
    "phone": "8074693258",
    "profile": "https://app.superinstajobs.com/uploads/1738859793805.6748.jpg"
  },
  "categories": {
    "id": 1,
    "name": "Builders",
    "image": "https://app.superinstajobs.com/uploads/1722582520107.6833.png",
    "status": 1,
    "isSubCategories": 1,
    "created": 0,
    "modified": 1722582520
  }
}
*/

  int? id;
  int? userId;
  String? title;
  int? categoryId;
  int? subCategoryId;
  int? devilryTime;
  int? isJobEnd;
  String? country;
  String? state;
  int? latitude;
  int? longitude;
  String? descriptions;
  int? assignUserId;
  String? locations;
  int? totalBudgets;
  int? isRaiseDispute;
  String? attachments;
  String? defaultVideoLink;
  int? acceptedBudget;
  int? isAssigned;
  int? isFeature;
  int? isAnyWhere;
  String? skills;
  int? priceForm;
  int? priceTo;
  String? experience;
  int? isBoosted;
  int? boostTime;
  int? disputeId;
  int? created;
  int? modified;
  int? isFav;
  int? totalProposals;
  int? isSendProposals;
  MyInstaJobsModelDataDataUsers? users;
  MyInstaJobsModelDataDataCategories? categories;

  MyInstaJobsModelDataData({
    this.id,
    this.userId,
    this.title,
    this.categoryId,
    this.subCategoryId,
    this.devilryTime,
    this.isJobEnd,
    this.country,
    this.state,
    this.latitude,
    this.longitude,
    this.descriptions,
    this.assignUserId,
    this.locations,
    this.totalBudgets,
    this.isRaiseDispute,
    this.attachments,
    this.defaultVideoLink,
    this.acceptedBudget,
    this.isAssigned,
    this.isFeature,
    this.isAnyWhere,
    this.skills,
    this.priceForm,
    this.priceTo,
    this.experience,
    this.isBoosted,
    this.boostTime,
    this.disputeId,
    this.created,
    this.modified,
    this.isFav,
    this.totalProposals,
    this.isSendProposals,
    this.users,
    this.categories,
  });
  MyInstaJobsModelDataData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    userId = json['userId']?.toInt();
    title = json['title']?.toString();
    categoryId = json['categoryId']?.toInt();
    subCategoryId = json['subCategoryId']?.toInt();
    devilryTime = json['devilryTime']?.toInt();
    isJobEnd = json['isJobEnd']?.toInt();
    country = json['country']?.toString();
    state = json['state']?.toString();
    latitude = json['latitude']?.toInt();
    longitude = json['longitude']?.toInt();
    descriptions = json['descriptions']?.toString();
    assignUserId = json['assignUserId']?.toInt();
    locations = json['locations']?.toString();
    totalBudgets = json['totalBudgets']?.toInt();
    isRaiseDispute = json['isRaiseDispute']?.toInt();
    attachments = json['attachments']?.toString();
    defaultVideoLink = json['defaultVideoLink']?.toString();
    acceptedBudget = json['acceptedBudget']?.toInt();
    isAssigned = json['isAssigned']?.toInt();
    isFeature = json['isFeature']?.toInt();
    isAnyWhere = json['isAnyWhere']?.toInt();
    skills = json['skills']?.toString();
    priceForm = json['priceForm']?.toInt();
    priceTo = json['priceTo']?.toInt();
    experience = json['experience']?.toString();
    isBoosted = json['isBoosted']?.toInt();
    boostTime = json['boostTime']?.toInt();
    disputeId = json['disputeId']?.toInt();
    created = json['created']?.toInt();
    modified = json['modified']?.toInt();
    isFav = json['isFav']?.toInt();
    totalProposals = json['totalProposals']?.toInt();
    isSendProposals = json['isSendProposals']?.toInt();
    users = (json['users'] != null) ? MyInstaJobsModelDataDataUsers.fromJson(json['users']) : null;
    categories = (json['categories'] != null) ? MyInstaJobsModelDataDataCategories.fromJson(json['categories']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['userId'] = userId;
    data['title'] = title;
    data['categoryId'] = categoryId;
    data['subCategoryId'] = subCategoryId;
    data['devilryTime'] = devilryTime;
    data['isJobEnd'] = isJobEnd;
    data['country'] = country;
    data['state'] = state;
    data['latitude'] = latitude;
    data['longitude'] = longitude;
    data['descriptions'] = descriptions;
    data['assignUserId'] = assignUserId;
    data['locations'] = locations;
    data['totalBudgets'] = totalBudgets;
    data['isRaiseDispute'] = isRaiseDispute;
    data['attachments'] = attachments;
    data['defaultVideoLink'] = defaultVideoLink;
    data['acceptedBudget'] = acceptedBudget;
    data['isAssigned'] = isAssigned;
    data['isFeature'] = isFeature;
    data['isAnyWhere'] = isAnyWhere;
    data['skills'] = skills;
    data['priceForm'] = priceForm;
    data['priceTo'] = priceTo;
    data['experience'] = experience;
    data['isBoosted'] = isBoosted;
    data['boostTime'] = boostTime;
    data['disputeId'] = disputeId;
    data['created'] = created;
    data['modified'] = modified;
    data['isFav'] = isFav;
    data['totalProposals'] = totalProposals;
    data['isSendProposals'] = isSendProposals;
    if (users != null) {
      data['users'] = users!.toJson();
    }
    if (categories != null) {
      data['categories'] = categories!.toJson();
    }
    return data;
  }
}

class MyInstaJobsModelData {
/*
{
  "data": [
    {
      "id": 1,
      "userId": 4,
      "title": "Need a Plumber for Tap fixing",
      "categoryId": 1,
      "subCategoryId": 3,
      "devilryTime": 1,
      "isJobEnd": 0,
      "country": "",
      "state": "",
      "latitude": 0,
      "longitude": 0,
      "descriptions": "Need a plumber to fix me bathroom tap urgently.",
      "assignUserId": 0,
      "locations": "",
      "totalBudgets": 500,
      "isRaiseDispute": 0,
      "attachments": "https://app.superinstajobs.com/uploads/1738862433368.4587.jpg",
      "defaultVideoLink": "",
      "acceptedBudget": 0,
      "isAssigned": 0,
      "isFeature": 0,
      "isAnyWhere": 1,
      "skills": "Plumber",
      "priceForm": 400,
      "priceTo": 400,
      "experience": "Expert",
      "isBoosted": 0,
      "boostTime": 0,
      "disputeId": 0,
      "created": 1738862433,
      "modified": 1738862433,
      "isFav": 0,
      "totalProposals": 1,
      "isSendProposals": 1,
      "users": {
        "id": 4,
        "name": "Jyoti",
        "email": "jyoti@gmail.com",
        "phone": "8074693258",
        "profile": "https://app.superinstajobs.com/uploads/1738859793805.6748.jpg"
      },
      "categories": {
        "id": 1,
        "name": "Builders",
        "image": "https://app.superinstajobs.com/uploads/1722582520107.6833.png",
        "status": 1,
        "isSubCategories": 1,
        "created": 0,
        "modified": 1722582520
      }
    }
  ],
  "pagination": {
    "currentPage": 1,
    "totalPage": 1,
    "totalRecord": 1,
    "limit": 8
  }
}
*/

  List<MyInstaJobsModelDataData?>? data;
  MyInstaJobsModelDataPagination? pagination;

  MyInstaJobsModelData({
    this.data,
    this.pagination,
  });
  MyInstaJobsModelData.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <MyInstaJobsModelDataData>[];
      v.forEach((v) {
        arr0.add(MyInstaJobsModelDataData.fromJson(v));
      });
      this.data = arr0;
    }
    pagination = (json['pagination'] != null) ? MyInstaJobsModelDataPagination.fromJson(json['pagination']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    if (pagination != null) {
      data['pagination'] = pagination!.toJson();
    }
    return data;
  }
}

class MyInstaJobsModel {
/*
{
  "success": true,
  "message": "Job listing",
  "status": 200,
  "data": {
    "data": [
      {
        "id": 1,
        "userId": 4,
        "title": "Need a Plumber for Tap fixing",
        "categoryId": 1,
        "subCategoryId": 3,
        "devilryTime": 1,
        "isJobEnd": 0,
        "country": "",
        "state": "",
        "latitude": 0,
        "longitude": 0,
        "descriptions": "Need a plumber to fix me bathroom tap urgently.",
        "assignUserId": 0,
        "locations": "",
        "totalBudgets": 500,
        "isRaiseDispute": 0,
        "attachments": "https://app.superinstajobs.com/uploads/1738862433368.4587.jpg",
        "defaultVideoLink": "",
        "acceptedBudget": 0,
        "isAssigned": 0,
        "isFeature": 0,
        "isAnyWhere": 1,
        "skills": "Plumber",
        "priceForm": 400,
        "priceTo": 400,
        "experience": "Expert",
        "isBoosted": 0,
        "boostTime": 0,
        "disputeId": 0,
        "created": 1738862433,
        "modified": 1738862433,
        "isFav": 0,
        "totalProposals": 1,
        "isSendProposals": 1,
        "users": {
          "id": 4,
          "name": "Jyoti",
          "email": "jyoti@gmail.com",
          "phone": "8074693258",
          "profile": "https://app.superinstajobs.com/uploads/1738859793805.6748.jpg"
        },
        "categories": {
          "id": 1,
          "name": "Builders",
          "image": "https://app.superinstajobs.com/uploads/1722582520107.6833.png",
          "status": 1,
          "isSubCategories": 1,
          "created": 0,
          "modified": 1722582520
        }
      }
    ],
    "pagination": {
      "currentPage": 1,
      "totalPage": 1,
      "totalRecord": 1,
      "limit": 8
    }
  }
}
*/

  bool? success;
  String? message;
  int? status;
  MyInstaJobsModelData? data;

  MyInstaJobsModel({
    this.success,
    this.message,
    this.status,
    this.data,
  });
  MyInstaJobsModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    status = json['status']?.toInt();
    data = (json['data'] != null) ? MyInstaJobsModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    data['status'] = status;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
