///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MyPortfolioModelDataPagination {
/*
{
  "currentPage": 1,
  "totalPage": 1,
  "totalRecord": 2,
  "limit": 10
}
*/

  int? currentPage;
  int? totalPage;
  int? totalRecord;
  int? limit;

  MyPortfolioModelDataPagination({
    this.currentPage,
    this.totalPage,
    this.totalRecord,
    this.limit,
  });
  MyPortfolioModelDataPagination.fromJson(Map<String, dynamic> json) {
    currentPage = json['currentPage']?.toInt();
    totalPage = json['totalPage']?.toInt();
    totalRecord = json['totalRecord']?.toInt();
    limit = json['limit']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['currentPage'] = currentPage;
    data['totalPage'] = totalPage;
    data['totalRecord'] = totalRecord;
    data['limit'] = limit;
    return data;
  }
}

class MyPortfolioModelDataData {
/*
{
  "id": 3,
  "userId": 2,
  "title": "Build Apps New",
  "description": "I  builds of multiple categories to ,u",
  "image": "https://app.superinstajobs.com/uploads/1739964948628.7424.jpg",
  "status": 1,
  "type": 0,
  "created": 1739964949,
  "modified": 1748504450
}
*/

  int? id;
  int? userId;
  String? title;
  String? description;
  String? image;
  int? status;
  int? type;
  int? created;
  int? modified;

  MyPortfolioModelDataData({
    this.id,
    this.userId,
    this.title,
    this.description,
    this.image,
    this.status,
    this.type,
    this.created,
    this.modified,
  });
  MyPortfolioModelDataData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    userId = json['userId']?.toInt();
    title = json['title']?.toString();
    description = json['description']?.toString();
    image = json['image']?.toString();
    status = json['status']?.toInt();
    type = json['type']?.toInt();
    created = json['created']?.toInt();
    modified = json['modified']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['userId'] = userId;
    data['title'] = title;
    data['description'] = description;
    data['image'] = image;
    data['status'] = status;
    data['type'] = type;
    data['created'] = created;
    data['modified'] = modified;
    return data;
  }
}

class MyPortfolioModelData {
/*
{
  "data": [
    {
      "id": 3,
      "userId": 2,
      "title": "Build Apps New",
      "description": "I  builds of multiple categories to ,u",
      "image": "https://app.superinstajobs.com/uploads/1739964948628.7424.jpg",
      "status": 1,
      "type": 0,
      "created": 1739964949,
      "modified": 1748504450
    }
  ],
  "pagination": {
    "currentPage": 1,
    "totalPage": 1,
    "totalRecord": 2,
    "limit": 10
  }
}
*/

  List<MyPortfolioModelDataData?>? data;
  MyPortfolioModelDataPagination? pagination;

  MyPortfolioModelData({
    this.data,
    this.pagination,
  });
  MyPortfolioModelData.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <MyPortfolioModelDataData>[];
      v.forEach((v) {
        arr0.add(MyPortfolioModelDataData.fromJson(v));
      });
      this.data = arr0;
    }
    pagination = (json['pagination'] != null) ? MyPortfolioModelDataPagination.fromJson(json['pagination']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    if (pagination != null) {
      data['pagination'] = pagination!.toJson();
    }
    return data;
  }
}

class MyPortfolioModel {
/*
{
  "success": true,
  "message": "User portfolios",
  "status": 200,
  "data": {
    "data": [
      {
        "id": 3,
        "userId": 2,
        "title": "Build Apps New",
        "description": "I  builds of multiple categories to ,u",
        "image": "https://app.superinstajobs.com/uploads/1739964948628.7424.jpg",
        "status": 1,
        "type": 0,
        "created": 1739964949,
        "modified": 1748504450
      }
    ],
    "pagination": {
      "currentPage": 1,
      "totalPage": 1,
      "totalRecord": 2,
      "limit": 10
    }
  }
}
*/

  bool? success;
  String? message;
  int? status;
  MyPortfolioModelData? data;

  MyPortfolioModel({
    this.success,
    this.message,
    this.status,
    this.data,
  });
  MyPortfolioModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    status = json['status']?.toInt();
    data = (json['data'] != null) ? MyPortfolioModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    data['status'] = status;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
