///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MyWalletModelDataPagination {
/*
{
  "currentPage": 1,
  "totalPage": 1,
  "totalRecord": 3,
  "limit": 10
}
*/

  int? currentPage;
  int? totalPage;
  int? totalRecord;
  int? limit;

  MyWalletModelDataPagination({
    this.currentPage,
    this.totalPage,
    this.totalRecord,
    this.limit,
  });
  MyWalletModelDataPagination.fromJson(Map<String, dynamic> json) {
    currentPage = json['currentPage']?.toInt();
    totalPage = json['totalPage']?.toInt();
    totalRecord = json['totalRecord']?.toInt();
    limit = json['limit']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['currentPage'] = currentPage;
    data['totalPage'] = totalPage;
    data['totalRecord'] = totalRecord;
    data['limit'] = limit;
    return data;
  }
}

class MyWalletModelDataDataPurchaseOffers {
/*
{
  "id": 3,
  "userId": 5,
  "offerId": 2,
  "userOfferId": 2,
  "status": 1,
  "paymentInfo": "{\"id\":8408031,\"tx_ref\":\"TX-1740422937991\",\"flw_ref\":\"FLW-MOCK-a83a4c302f31722d042db26e5e9baa8b\",\"device_fingerprint\":\"N/A\",\"amount\":210,\"charged_amount\":210,\"app_fee\":2.94,\"merchant_fee\":0,\"processor_response\":\"successful\",\"auth_model\":\"VBVSECURECODE\",\"currency\":\"NGN\",\"ip\":\"54.75.161.64\",\"narration\":\"CARD Transaction \",\"status\":\"successful\",\"auth_url\":\"https://ravesandboxapi.flutterwave.com/mockvbvpage?ref=FLW-MOCK-a83a4c302f31722d042db26e5e9baa8b&code=00&message=Approved.%20Successful&receiptno=RN1740422940650\",\"payment_type\":\"card\",\"plan\":null,\"fraud_status\":\"ok\",\"charge_type\":\"normal\",\"created_at\":\"2025-02-24T18:49:00.000Z\",\"account_id\":2564335,\"customer\":{\"id\":2583937,\"phone_number\":\"7888644412\",\"name\":\"Jyoti Builders\",\"email\":\"jyoti@yopmail.com\",\"created_at\":\"2025-02-06T16:42:15.000Z\"},\"card\":{\"first_6digits\":\"553188\",\"last_4digits\":\"2950\",\"issuer\":\"MASTERCARD  CREDIT\",\"country\":\"NG\",\"type\":\"MASTERCARD\",\"expiry\":\"09/55\"}}",
  "amount": 2000,
  "offerTime": 4,
  "adOns": [
    ""
  ],
  "isExtend": 0,
  "nextDeliveryMessage": "",
  "nextDeliveryDate": 0,
  "paymentStatus": 1,
  "created": 1739858428,
  "modified": 1740422951
}
*/

  int? id;
  int? userId;
  int? offerId;
  int? userOfferId;
  int? status;
  String? paymentInfo;
  int? amount;
  int? offerTime;
  List<String?>? adOns;
  int? isExtend;
  String? nextDeliveryMessage;
  int? nextDeliveryDate;
  int? paymentStatus;
  int? created;
  int? modified;

  MyWalletModelDataDataPurchaseOffers({
    this.id,
    this.userId,
    this.offerId,
    this.userOfferId,
    this.status,
    this.paymentInfo,
    this.amount,
    this.offerTime,
    this.adOns,
    this.isExtend,
    this.nextDeliveryMessage,
    this.nextDeliveryDate,
    this.paymentStatus,
    this.created,
    this.modified,
  });
  MyWalletModelDataDataPurchaseOffers.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    userId = json['userId']?.toInt();
    offerId = json['offerId']?.toInt();
    userOfferId = json['userOfferId']?.toInt();
    status = json['status']?.toInt();
    paymentInfo = json['paymentInfo']?.toString();
    amount = json['amount']?.toInt();
    offerTime = json['offerTime']?.toInt();
    if (json['adOns'] != null) {
      final v = json['adOns'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      adOns = arr0;
    }
    isExtend = json['isExtend']?.toInt();
    nextDeliveryMessage = json['nextDeliveryMessage']?.toString();
    nextDeliveryDate = json['nextDeliveryDate']?.toInt();
    paymentStatus = json['paymentStatus']?.toInt();
    created = json['created']?.toInt();
    modified = json['modified']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['userId'] = userId;
    data['offerId'] = offerId;
    data['userOfferId'] = userOfferId;
    data['status'] = status;
    data['paymentInfo'] = paymentInfo;
    data['amount'] = amount;
    data['offerTime'] = offerTime;
    if (adOns != null) {
      final v = adOns;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['adOns'] = arr0;
    }
    data['isExtend'] = isExtend;
    data['nextDeliveryMessage'] = nextDeliveryMessage;
    data['nextDeliveryDate'] = nextDeliveryDate;
    data['paymentStatus'] = paymentStatus;
    data['created'] = created;
    data['modified'] = modified;
    return data;
  }
}

class MyWalletModelDataData {
/*
{
  "id": 29,
  "walletId": 2,
  "amount": 1800,
  "transaction_type": "credit",
  "reference": "",
  "status": "pending",
  "purchaseOfferId": 3,
  "jobId": 0,
  "bookingId": 0,
  "MileStoneId": 0,
  "couponCode": "",
  "coinValue": 0,
  "type": 4,
  "offerId": 0,
  "bookingAdOnId": 0,
  "userId": 0,
  "created": 1740422951,
  "modified": 1740422951,
  "purchaseOffers": {
    "id": 3,
    "userId": 5,
    "offerId": 2,
    "userOfferId": 2,
    "status": 1,
    "paymentInfo": "{\"id\":8408031,\"tx_ref\":\"TX-1740422937991\",\"flw_ref\":\"FLW-MOCK-a83a4c302f31722d042db26e5e9baa8b\",\"device_fingerprint\":\"N/A\",\"amount\":210,\"charged_amount\":210,\"app_fee\":2.94,\"merchant_fee\":0,\"processor_response\":\"successful\",\"auth_model\":\"VBVSECURECODE\",\"currency\":\"NGN\",\"ip\":\"54.75.161.64\",\"narration\":\"CARD Transaction \",\"status\":\"successful\",\"auth_url\":\"https://ravesandboxapi.flutterwave.com/mockvbvpage?ref=FLW-MOCK-a83a4c302f31722d042db26e5e9baa8b&code=00&message=Approved.%20Successful&receiptno=RN1740422940650\",\"payment_type\":\"card\",\"plan\":null,\"fraud_status\":\"ok\",\"charge_type\":\"normal\",\"created_at\":\"2025-02-24T18:49:00.000Z\",\"account_id\":2564335,\"customer\":{\"id\":2583937,\"phone_number\":\"7888644412\",\"name\":\"Jyoti Builders\",\"email\":\"jyoti@yopmail.com\",\"created_at\":\"2025-02-06T16:42:15.000Z\"},\"card\":{\"first_6digits\":\"553188\",\"last_4digits\":\"2950\",\"issuer\":\"MASTERCARD  CREDIT\",\"country\":\"NG\",\"type\":\"MASTERCARD\",\"expiry\":\"09/55\"}}",
    "amount": 2000,
    "offerTime": 4,
    "adOns": [
      ""
    ],
    "isExtend": 0,
    "nextDeliveryMessage": "",
    "nextDeliveryDate": 0,
    "paymentStatus": 1,
    "created": 1739858428,
    "modified": 1740422951
  }
}
*/

  int? id;
  int? walletId;
  int? amount;
  String? transactionType;
  String? reference;
  String? status;
  int? purchaseOfferId;
  int? jobId;
  int? bookingId;
  int? MileStoneId;
  String? couponCode;
  int? coinValue;
  int? type;
  int? offerId;
  int? bookingAdOnId;
  int? userId;
  int? created;
  int? modified;
  MyWalletModelDataDataPurchaseOffers? purchaseOffers;

  MyWalletModelDataData({
    this.id,
    this.walletId,
    this.amount,
    this.transactionType,
    this.reference,
    this.status,
    this.purchaseOfferId,
    this.jobId,
    this.bookingId,
    this.MileStoneId,
    this.couponCode,
    this.coinValue,
    this.type,
    this.offerId,
    this.bookingAdOnId,
    this.userId,
    this.created,
    this.modified,
    this.purchaseOffers,
  });
  MyWalletModelDataData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    walletId = json['walletId']?.toInt();
    amount = json['amount']?.toInt();
    transactionType = json['transaction_type']?.toString();
    reference = json['reference']?.toString();
    status = json['status']?.toString();
    purchaseOfferId = json['purchaseOfferId']?.toInt();
    jobId = json['jobId']?.toInt();
    bookingId = json['bookingId']?.toInt();
    MileStoneId = json['MileStoneId']?.toInt();
    couponCode = json['couponCode']?.toString();
    coinValue = json['coinValue']?.toInt();
    type = json['type']?.toInt();
    offerId = json['offerId']?.toInt();
    bookingAdOnId = json['bookingAdOnId']?.toInt();
    userId = json['userId']?.toInt();
    created = json['created']?.toInt();
    modified = json['modified']?.toInt();
    purchaseOffers = (json['purchaseOffers'] != null) ? MyWalletModelDataDataPurchaseOffers.fromJson(json['purchaseOffers']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['walletId'] = walletId;
    data['amount'] = amount;
    data['transaction_type'] = transactionType;
    data['reference'] = reference;
    data['status'] = status;
    data['purchaseOfferId'] = purchaseOfferId;
    data['jobId'] = jobId;
    data['bookingId'] = bookingId;
    data['MileStoneId'] = MileStoneId;
    data['couponCode'] = couponCode;
    data['coinValue'] = coinValue;
    data['type'] = type;
    data['offerId'] = offerId;
    data['bookingAdOnId'] = bookingAdOnId;
    data['userId'] = userId;
    data['created'] = created;
    data['modified'] = modified;
    if (purchaseOffers != null) {
      data['purchaseOffers'] = purchaseOffers!.toJson();
    }
    return data;
  }
}

class MyWalletModelData {
/*
{
  "data": [
    {
      "id": 29,
      "walletId": 2,
      "amount": 1800,
      "transaction_type": "credit",
      "reference": "",
      "status": "pending",
      "purchaseOfferId": 3,
      "jobId": 0,
      "bookingId": 0,
      "MileStoneId": 0,
      "couponCode": "",
      "coinValue": 0,
      "type": 4,
      "offerId": 0,
      "bookingAdOnId": 0,
      "userId": 0,
      "created": 1740422951,
      "modified": 1740422951,
      "purchaseOffers": {
        "id": 3,
        "userId": 5,
        "offerId": 2,
        "userOfferId": 2,
        "status": 1,
        "paymentInfo": "{\"id\":8408031,\"tx_ref\":\"TX-1740422937991\",\"flw_ref\":\"FLW-MOCK-a83a4c302f31722d042db26e5e9baa8b\",\"device_fingerprint\":\"N/A\",\"amount\":210,\"charged_amount\":210,\"app_fee\":2.94,\"merchant_fee\":0,\"processor_response\":\"successful\",\"auth_model\":\"VBVSECURECODE\",\"currency\":\"NGN\",\"ip\":\"54.75.161.64\",\"narration\":\"CARD Transaction \",\"status\":\"successful\",\"auth_url\":\"https://ravesandboxapi.flutterwave.com/mockvbvpage?ref=FLW-MOCK-a83a4c302f31722d042db26e5e9baa8b&code=00&message=Approved.%20Successful&receiptno=RN1740422940650\",\"payment_type\":\"card\",\"plan\":null,\"fraud_status\":\"ok\",\"charge_type\":\"normal\",\"created_at\":\"2025-02-24T18:49:00.000Z\",\"account_id\":2564335,\"customer\":{\"id\":2583937,\"phone_number\":\"7888644412\",\"name\":\"Jyoti Builders\",\"email\":\"jyoti@yopmail.com\",\"created_at\":\"2025-02-06T16:42:15.000Z\"},\"card\":{\"first_6digits\":\"553188\",\"last_4digits\":\"2950\",\"issuer\":\"MASTERCARD  CREDIT\",\"country\":\"NG\",\"type\":\"MASTERCARD\",\"expiry\":\"09/55\"}}",
        "amount": 2000,
        "offerTime": 4,
        "adOns": [
          ""
        ],
        "isExtend": 0,
        "nextDeliveryMessage": "",
        "nextDeliveryDate": 0,
        "paymentStatus": 1,
        "created": 1739858428,
        "modified": 1740422951
      }
    }
  ],
  "pagination": {
    "currentPage": 1,
    "totalPage": 1,
    "totalRecord": 3,
    "limit": 10
  }
}
*/

  List<MyWalletModelDataData?>? data;
  MyWalletModelDataPagination? pagination;

  MyWalletModelData({
    this.data,
    this.pagination,
  });
  MyWalletModelData.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <MyWalletModelDataData>[];
      v.forEach((v) {
        arr0.add(MyWalletModelDataData.fromJson(v));
      });
      this.data = arr0;
    }
    pagination = (json['pagination'] != null) ? MyWalletModelDataPagination.fromJson(json['pagination']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    if (pagination != null) {
      data['pagination'] = pagination!.toJson();
    }
    return data;
  }
}

class MyWalletModel {
/*
{
  "success": true,
  "message": "Transaction get successfully",
  "status": 200,
  "data": {
    "data": [
      {
        "id": 29,
        "walletId": 2,
        "amount": 1800,
        "transaction_type": "credit",
        "reference": "",
        "status": "pending",
        "purchaseOfferId": 3,
        "jobId": 0,
        "bookingId": 0,
        "MileStoneId": 0,
        "couponCode": "",
        "coinValue": 0,
        "type": 4,
        "offerId": 0,
        "bookingAdOnId": 0,
        "userId": 0,
        "created": 1740422951,
        "modified": 1740422951,
        "purchaseOffers": {
          "id": 3,
          "userId": 5,
          "offerId": 2,
          "userOfferId": 2,
          "status": 1,
          "paymentInfo": "{\"id\":8408031,\"tx_ref\":\"TX-1740422937991\",\"flw_ref\":\"FLW-MOCK-a83a4c302f31722d042db26e5e9baa8b\",\"device_fingerprint\":\"N/A\",\"amount\":210,\"charged_amount\":210,\"app_fee\":2.94,\"merchant_fee\":0,\"processor_response\":\"successful\",\"auth_model\":\"VBVSECURECODE\",\"currency\":\"NGN\",\"ip\":\"54.75.161.64\",\"narration\":\"CARD Transaction \",\"status\":\"successful\",\"auth_url\":\"https://ravesandboxapi.flutterwave.com/mockvbvpage?ref=FLW-MOCK-a83a4c302f31722d042db26e5e9baa8b&code=00&message=Approved.%20Successful&receiptno=RN1740422940650\",\"payment_type\":\"card\",\"plan\":null,\"fraud_status\":\"ok\",\"charge_type\":\"normal\",\"created_at\":\"2025-02-24T18:49:00.000Z\",\"account_id\":2564335,\"customer\":{\"id\":2583937,\"phone_number\":\"7888644412\",\"name\":\"Jyoti Builders\",\"email\":\"jyoti@yopmail.com\",\"created_at\":\"2025-02-06T16:42:15.000Z\"},\"card\":{\"first_6digits\":\"553188\",\"last_4digits\":\"2950\",\"issuer\":\"MASTERCARD  CREDIT\",\"country\":\"NG\",\"type\":\"MASTERCARD\",\"expiry\":\"09/55\"}}",
          "amount": 2000,
          "offerTime": 4,
          "adOns": [
            ""
          ],
          "isExtend": 0,
          "nextDeliveryMessage": "",
          "nextDeliveryDate": 0,
          "paymentStatus": 1,
          "created": 1739858428,
          "modified": 1740422951
        }
      }
    ],
    "pagination": {
      "currentPage": 1,
      "totalPage": 1,
      "totalRecord": 3,
      "limit": 10
    }
  }
}
*/

  bool? success;
  String? message;
  int? status;
  MyWalletModelData? data;

  MyWalletModel({
    this.success,
    this.message,
    this.status,
    this.data,
  });
  MyWalletModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    status = json['status']?.toInt();
    data = (json['data'] != null) ? MyWalletModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    data['status'] = status;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
