///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class NotificationModelDataNotificationsPagination {
/*
{
  "currentPage": 1,
  "totalPage": 1,
  "totalRecord": 13,
  "limit": 30
}
*/

  int? currentPage;
  int? totalPage;
  int? totalRecord;
  int? limit;

  NotificationModelDataNotificationsPagination({
    this.currentPage,
    this.totalPage,
    this.totalRecord,
    this.limit,
  });
  NotificationModelDataNotificationsPagination.fromJson(Map<String, dynamic> json) {
    currentPage = json['currentPage']?.toInt();
    totalPage = json['totalPage']?.toInt();
    totalRecord = json['totalRecord']?.toInt();
    limit = json['limit']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['currentPage'] = currentPage;
    data['totalPage'] = totalPage;
    data['totalRecord'] = totalRecord;
    data['limit'] = limit;
    return data;
  }
}

class NotificationModelDataNotificationsDataPurchaseOffers {
/*
{
  "id": 1,
  "userId": 5,
  "offerId": 1,
  "userOfferId": 2,
  "status": 1,
  "paymentInfo": "adOns",
  "amount": 5000,
  "offerTime": 2,
  "adOns": [
    ""
  ],
  "isExtend": 0,
  "nextDeliveryMessage": "",
  "nextDeliveryDate": 0,
  "paymentStatus": 0,
  "created": 1739188945,
  "modified": 1739188945
}
*/

  int? id;
  int? userId;
  int? offerId;
  int? userOfferId;
  int? status;
  String? paymentInfo;
  int? amount;
  int? offerTime;
  List<String?>? adOns;
  int? isExtend;
  String? nextDeliveryMessage;
  int? nextDeliveryDate;
  int? paymentStatus;
  int? created;
  int? modified;

  NotificationModelDataNotificationsDataPurchaseOffers({
    this.id,
    this.userId,
    this.offerId,
    this.userOfferId,
    this.status,
    this.paymentInfo,
    this.amount,
    this.offerTime,
    this.adOns,
    this.isExtend,
    this.nextDeliveryMessage,
    this.nextDeliveryDate,
    this.paymentStatus,
    this.created,
    this.modified,
  });
  NotificationModelDataNotificationsDataPurchaseOffers.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    userId = json['userId']?.toInt();
    offerId = json['offerId']?.toInt();
    userOfferId = json['userOfferId']?.toInt();
    status = json['status']?.toInt();
    paymentInfo = json['paymentInfo']?.toString();
    amount = json['amount']?.toInt();
    offerTime = json['offerTime']?.toInt();
    if (json['adOns'] != null) {
      final v = json['adOns'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      adOns = arr0;
    }
    isExtend = json['isExtend']?.toInt();
    nextDeliveryMessage = json['nextDeliveryMessage']?.toString();
    nextDeliveryDate = json['nextDeliveryDate']?.toInt();
    paymentStatus = json['paymentStatus']?.toInt();
    created = json['created']?.toInt();
    modified = json['modified']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['userId'] = userId;
    data['offerId'] = offerId;
    data['userOfferId'] = userOfferId;
    data['status'] = status;
    data['paymentInfo'] = paymentInfo;
    data['amount'] = amount;
    data['offerTime'] = offerTime;
    if (adOns != null) {
      final v = adOns;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['adOns'] = arr0;
    }
    data['isExtend'] = isExtend;
    data['nextDeliveryMessage'] = nextDeliveryMessage;
    data['nextDeliveryDate'] = nextDeliveryDate;
    data['paymentStatus'] = paymentStatus;
    data['created'] = created;
    data['modified'] = modified;
    return data;
  }
}

class NotificationModelDataNotificationsDataUsersOffersAdOn {
/*
{
  "price": "200",
  "title": "Cleaning",
  "workingDays": "1 Day"
}
*/

  String? price;
  String? title;
  String? workingDays;

  NotificationModelDataNotificationsDataUsersOffersAdOn({
    this.price,
    this.title,
    this.workingDays,
  });
  NotificationModelDataNotificationsDataUsersOffersAdOn.fromJson(Map<String, dynamic> json) {
    price = json['price']?.toString();
    title = json['title']?.toString();
    workingDays = json['workingDays']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['price'] = price;
    data['title'] = title;
    data['workingDays'] = workingDays;
    return data;
  }
}

class NotificationModelDataNotificationsDataUsersOffers {
/*
{
  "id": 1,
  "userId": 2,
  "name": "Plumber Work",
  "price": 5000,
  "description": "In this I'll complete your bathroom",
  "totalSold": 0,
  "deliveryTime": 2,
  "image": "",
  "adOn": [
    {
      "price": "200",
      "title": "Cleaning",
      "workingDays": "1 Day"
    }
  ],
  "isBoosted": 0,
  "boostTime": 0,
  "created": 1738859266,
  "modified": 1739678580
}
*/

  int? id;
  int? userId;
  String? name;
  int? price;
  String? description;
  int? totalSold;
  int? deliveryTime;
  String? image;
  List<NotificationModelDataNotificationsDataUsersOffersAdOn?>? adOn;
  int? isBoosted;
  int? boostTime;
  int? created;
  int? modified;

  NotificationModelDataNotificationsDataUsersOffers({
    this.id,
    this.userId,
    this.name,
    this.price,
    this.description,
    this.totalSold,
    this.deliveryTime,
    this.image,
    this.adOn,
    this.isBoosted,
    this.boostTime,
    this.created,
    this.modified,
  });
  NotificationModelDataNotificationsDataUsersOffers.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    userId = json['userId']?.toInt();
    name = json['name']?.toString();
    price = json['price']?.toInt();
    description = json['description']?.toString();
    totalSold = json['totalSold']?.toInt();
    deliveryTime = json['deliveryTime']?.toInt();
    image = json['image']?.toString();
    if (json['adOn'] != null) {
      final v = json['adOn'];
      final arr0 = <NotificationModelDataNotificationsDataUsersOffersAdOn>[];
      v.forEach((v) {
        arr0.add(NotificationModelDataNotificationsDataUsersOffersAdOn.fromJson(v));
      });
      adOn = arr0;
    }
    isBoosted = json['isBoosted']?.toInt();
    boostTime = json['boostTime']?.toInt();
    created = json['created']?.toInt();
    modified = json['modified']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['userId'] = userId;
    data['name'] = name;
    data['price'] = price;
    data['description'] = description;
    data['totalSold'] = totalSold;
    data['deliveryTime'] = deliveryTime;
    data['image'] = image;
    if (adOn != null) {
      final v = adOn;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['adOn'] = arr0;
    }
    data['isBoosted'] = isBoosted;
    data['boostTime'] = boostTime;
    data['created'] = created;
    data['modified'] = modified;
    return data;
  }
}

class NotificationModelDataNotificationsData {
/*
{
  "id": 5,
  "userId": 2,
  "text": "Offer Buy by User",
  "jobId": 0,
  "notificationType": 16,
  "offerId": 1,
  "purchaseOfferId": 1,
  "mileStoneId": 0,
  "isRead": 1,
  "created": 1739188945,
  "modified": 1748669013,
  "usersOffers": {
    "id": 1,
    "userId": 2,
    "name": "Plumber Work",
    "price": 5000,
    "description": "In this I'll complete your bathroom",
    "totalSold": 0,
    "deliveryTime": 2,
    "image": "",
    "adOn": [
      {
        "price": "200",
        "title": "Cleaning",
        "workingDays": "1 Day"
      }
    ],
    "isBoosted": 0,
    "boostTime": 0,
    "created": 1738859266,
    "modified": 1739678580
  },
  "purchaseOffers": {
    "id": 1,
    "userId": 5,
    "offerId": 1,
    "userOfferId": 2,
    "status": 1,
    "paymentInfo": "adOns",
    "amount": 5000,
    "offerTime": 2,
    "adOns": [
      ""
    ],
    "isExtend": 0,
    "nextDeliveryMessage": "",
    "nextDeliveryDate": 0,
    "paymentStatus": 0,
    "created": 1739188945,
    "modified": 1739188945
  }
}
*/

  int? id;
  int? userId;
  String? text;
  int? jobId;
  int? notificationType;
  int? offerId;
  int? purchaseOfferId;
  int? mileStoneId;
  int? isRead;
  int? created;
  int? modified;
  NotificationModelDataNotificationsDataUsersOffers? usersOffers;
  NotificationModelDataNotificationsDataPurchaseOffers? purchaseOffers;

  NotificationModelDataNotificationsData({
    this.id,
    this.userId,
    this.text,
    this.jobId,
    this.notificationType,
    this.offerId,
    this.purchaseOfferId,
    this.mileStoneId,
    this.isRead,
    this.created,
    this.modified,
    this.usersOffers,
    this.purchaseOffers,
  });
  NotificationModelDataNotificationsData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    userId = json['userId']?.toInt();
    text = json['text']?.toString();
    jobId = json['jobId']?.toInt();
    notificationType = json['notificationType']?.toInt();
    offerId = json['offerId']?.toInt();
    purchaseOfferId = json['purchaseOfferId']?.toInt();
    mileStoneId = json['mileStoneId']?.toInt();
    isRead = json['isRead']?.toInt();
    created = json['created']?.toInt();
    modified = json['modified']?.toInt();
    usersOffers = (json['usersOffers'] != null) ? NotificationModelDataNotificationsDataUsersOffers.fromJson(json['usersOffers']) : null;
    purchaseOffers = (json['purchaseOffers'] != null) ? NotificationModelDataNotificationsDataPurchaseOffers.fromJson(json['purchaseOffers']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['userId'] = userId;
    data['text'] = text;
    data['jobId'] = jobId;
    data['notificationType'] = notificationType;
    data['offerId'] = offerId;
    data['purchaseOfferId'] = purchaseOfferId;
    data['mileStoneId'] = mileStoneId;
    data['isRead'] = isRead;
    data['created'] = created;
    data['modified'] = modified;
    if (usersOffers != null) {
      data['usersOffers'] = usersOffers!.toJson();
    }
    if (purchaseOffers != null) {
      data['purchaseOffers'] = purchaseOffers!.toJson();
    }
    return data;
  }
}

class NotificationModelDataNotifications {
/*
{
  "data": [
    {
      "id": 5,
      "userId": 2,
      "text": "Offer Buy by User",
      "jobId": 0,
      "notificationType": 16,
      "offerId": 1,
      "purchaseOfferId": 1,
      "mileStoneId": 0,
      "isRead": 1,
      "created": 1739188945,
      "modified": 1748669013,
      "usersOffers": {
        "id": 1,
        "userId": 2,
        "name": "Plumber Work",
        "price": 5000,
        "description": "In this I'll complete your bathroom",
        "totalSold": 0,
        "deliveryTime": 2,
        "image": "",
        "adOn": [
          {
            "price": "200",
            "title": "Cleaning",
            "workingDays": "1 Day"
          }
        ],
        "isBoosted": 0,
        "boostTime": 0,
        "created": 1738859266,
        "modified": 1739678580
      },
      "purchaseOffers": {
        "id": 1,
        "userId": 5,
        "offerId": 1,
        "userOfferId": 2,
        "status": 1,
        "paymentInfo": "adOns",
        "amount": 5000,
        "offerTime": 2,
        "adOns": [
          ""
        ],
        "isExtend": 0,
        "nextDeliveryMessage": "",
        "nextDeliveryDate": 0,
        "paymentStatus": 0,
        "created": 1739188945,
        "modified": 1739188945
      }
    }
  ],
  "pagination": {
    "currentPage": 1,
    "totalPage": 1,
    "totalRecord": 13,
    "limit": 30
  }
}
*/

  List<NotificationModelDataNotificationsData?>? data;
  NotificationModelDataNotificationsPagination? pagination;

  NotificationModelDataNotifications({
    this.data,
    this.pagination,
  });
  NotificationModelDataNotifications.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <NotificationModelDataNotificationsData>[];
      v.forEach((v) {
        arr0.add(NotificationModelDataNotificationsData.fromJson(v));
      });
      this.data = arr0;
    }
    pagination = (json['pagination'] != null) ? NotificationModelDataNotificationsPagination.fromJson(json['pagination']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    if (pagination != null) {
      data['pagination'] = pagination!.toJson();
    }
    return data;
  }
}

class NotificationModelData {
/*
{
  "notifications": {
    "data": [
      {
        "id": 5,
        "userId": 2,
        "text": "Offer Buy by User",
        "jobId": 0,
        "notificationType": 16,
        "offerId": 1,
        "purchaseOfferId": 1,
        "mileStoneId": 0,
        "isRead": 1,
        "created": 1739188945,
        "modified": 1748669013,
        "usersOffers": {
          "id": 1,
          "userId": 2,
          "name": "Plumber Work",
          "price": 5000,
          "description": "In this I'll complete your bathroom",
          "totalSold": 0,
          "deliveryTime": 2,
          "image": "",
          "adOn": [
            {
              "price": "200",
              "title": "Cleaning",
              "workingDays": "1 Day"
            }
          ],
          "isBoosted": 0,
          "boostTime": 0,
          "created": 1738859266,
          "modified": 1739678580
        },
        "purchaseOffers": {
          "id": 1,
          "userId": 5,
          "offerId": 1,
          "userOfferId": 2,
          "status": 1,
          "paymentInfo": "adOns",
          "amount": 5000,
          "offerTime": 2,
          "adOns": [
            ""
          ],
          "isExtend": 0,
          "nextDeliveryMessage": "",
          "nextDeliveryDate": 0,
          "paymentStatus": 0,
          "created": 1739188945,
          "modified": 1739188945
        }
      }
    ],
    "pagination": {
      "currentPage": 1,
      "totalPage": 1,
      "totalRecord": 13,
      "limit": 30
    }
  },
  "totalNotificationUnReadCount": 0
}
*/

  NotificationModelDataNotifications? notifications;
  int? totalNotificationUnReadCount;

  NotificationModelData({
    this.notifications,
    this.totalNotificationUnReadCount,
  });
  NotificationModelData.fromJson(Map<String, dynamic> json) {
    notifications = (json['notifications'] != null) ? NotificationModelDataNotifications.fromJson(json['notifications']) : null;
    totalNotificationUnReadCount = json['totalNotificationUnReadCount']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (notifications != null) {
      data['notifications'] = notifications!.toJson();
    }
    data['totalNotificationUnReadCount'] = totalNotificationUnReadCount;
    return data;
  }
}

class NotificationModel {
/*
{
  "success": true,
  "message": "Notification list",
  "status": 200,
  "data": {
    "notifications": {
      "data": [
        {
          "id": 5,
          "userId": 2,
          "text": "Offer Buy by User",
          "jobId": 0,
          "notificationType": 16,
          "offerId": 1,
          "purchaseOfferId": 1,
          "mileStoneId": 0,
          "isRead": 1,
          "created": 1739188945,
          "modified": 1748669013,
          "usersOffers": {
            "id": 1,
            "userId": 2,
            "name": "Plumber Work",
            "price": 5000,
            "description": "In this I'll complete your bathroom",
            "totalSold": 0,
            "deliveryTime": 2,
            "image": "",
            "adOn": [
              {
                "price": "200",
                "title": "Cleaning",
                "workingDays": "1 Day"
              }
            ],
            "isBoosted": 0,
            "boostTime": 0,
            "created": 1738859266,
            "modified": 1739678580
          },
          "purchaseOffers": {
            "id": 1,
            "userId": 5,
            "offerId": 1,
            "userOfferId": 2,
            "status": 1,
            "paymentInfo": "adOns",
            "amount": 5000,
            "offerTime": 2,
            "adOns": [
              ""
            ],
            "isExtend": 0,
            "nextDeliveryMessage": "",
            "nextDeliveryDate": 0,
            "paymentStatus": 0,
            "created": 1739188945,
            "modified": 1739188945
          }
        }
      ],
      "pagination": {
        "currentPage": 1,
        "totalPage": 1,
        "totalRecord": 13,
        "limit": 30
      }
    },
    "totalNotificationUnReadCount": 0
  }
}
*/

  bool? success;
  String? message;
  int? status;
  NotificationModelData? data;

  NotificationModel({
    this.success,
    this.message,
    this.status,
    this.data,
  });
  NotificationModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    status = json['status']?.toInt();
    data = (json['data'] != null) ? NotificationModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    data['status'] = status;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
