///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class OfferTabModelDataPagination {
/*
{
  "currentPage": 1,
  "totalPage": 1,
  "totalRecord": 2,
  "limit": 10
}
*/

  int? currentPage;
  int? totalPage;
  int? totalRecord;
  int? limit;

  OfferTabModelDataPagination({
    this.currentPage,
    this.totalPage,
    this.totalRecord,
    this.limit,
  });
  OfferTabModelDataPagination.fromJson(Map<String, dynamic> json) {
    currentPage = json['currentPage']?.toInt();
    totalPage = json['totalPage']?.toInt();
    totalRecord = json['totalRecord']?.toInt();
    limit = json['limit']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['currentPage'] = currentPage;
    data['totalPage'] = totalPage;
    data['totalRecord'] = totalRecord;
    data['limit'] = limit;
    return data;
  }
}

class OfferTabModelDataDataOfferImages {
/*
{
  "id": 5,
  "offerId": 2,
  "attachments": "https://app.superinstajobs.com/uploads/1738859997396.106.jpg",
  "created": 1738859997,
  "modified": 1738859997
}
*/

  int? id;
  int? offerId;
  String? attachments;
  int? created;
  int? modified;

  OfferTabModelDataDataOfferImages({
    this.id,
    this.offerId,
    this.attachments,
    this.created,
    this.modified,
  });
  OfferTabModelDataDataOfferImages.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    offerId = json['offerId']?.toInt();
    attachments = json['attachments']?.toString();
    created = json['created']?.toInt();
    modified = json['modified']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['offerId'] = offerId;
    data['attachments'] = attachments;
    data['created'] = created;
    data['modified'] = modified;
    return data;
  }
}

class OfferTabModelDataDataAdOn {
/*
{
  "price": "2000",
  "title": "Setting Tiles In Walls of Room",
  "workingDays": "2 Days"
}
*/

  String? price;
  String? title;
  String? workingDays;

  OfferTabModelDataDataAdOn({
    this.price,
    this.title,
    this.workingDays,
  });
  OfferTabModelDataDataAdOn.fromJson(Map<String, dynamic> json) {
    price = json['price']?.toString();
    title = json['title']?.toString();
    workingDays = json['workingDays']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['price'] = price;
    data['title'] = title;
    data['workingDays'] = workingDays;
    return data;
  }
}

class OfferTabModelDataData {
/*
{
  "id": 2,
  "userId": 2,
  "name": "Tiles Setup In Room",
  "price": 2000,
  "description": "Setting tiles in a room.",
  "totalSold": 1,
  "deliveryTime": 4,
  "image": "",
  "adOn": [
    {
      "price": "2000",
      "title": "Setting Tiles In Walls of Room",
      "workingDays": "2 Days"
    }
  ],
  "isBoosted": 0,
  "boostTime": 0,
  "created": 1738859997,
  "modified": 1742060161,
  "isFavOffer": 0,
  "rating": "0.0",
  "offerImages": [
    {
      "id": 5,
      "offerId": 2,
      "attachments": "https://app.superinstajobs.com/uploads/1738859997396.106.jpg",
      "created": 1738859997,
      "modified": 1738859997
    }
  ]
}
*/

  int? id;
  int? userId;
  String? name;
  int? price;
  String? description;
  int? totalSold;
  int? deliveryTime;
  String? image;
  List<OfferTabModelDataDataAdOn?>? adOn;
  int? isBoosted;
  int? boostTime;
  int? created;
  int? modified;
  int? isFavOffer;
  String? rating;
  List<OfferTabModelDataDataOfferImages?>? offerImages;

  OfferTabModelDataData({
    this.id,
    this.userId,
    this.name,
    this.price,
    this.description,
    this.totalSold,
    this.deliveryTime,
    this.image,
    this.adOn,
    this.isBoosted,
    this.boostTime,
    this.created,
    this.modified,
    this.isFavOffer,
    this.rating,
    this.offerImages,
  });
  OfferTabModelDataData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    userId = json['userId']?.toInt();
    name = json['name']?.toString();
    price = json['price']?.toInt();
    description = json['description']?.toString();
    totalSold = json['totalSold']?.toInt();
    deliveryTime = json['deliveryTime']?.toInt();
    image = json['image']?.toString();
    if (json['adOn'] != null) {
      final v = json['adOn'];
      final arr0 = <OfferTabModelDataDataAdOn>[];
      v.forEach((v) {
        arr0.add(OfferTabModelDataDataAdOn.fromJson(v));
      });
      adOn = arr0;
    }
    isBoosted = json['isBoosted']?.toInt();
    boostTime = json['boostTime']?.toInt();
    created = json['created']?.toInt();
    modified = json['modified']?.toInt();
    isFavOffer = json['isFavOffer']?.toInt();
    rating = json['rating']?.toString();
    if (json['offerImages'] != null) {
      final v = json['offerImages'];
      final arr0 = <OfferTabModelDataDataOfferImages>[];
      v.forEach((v) {
        arr0.add(OfferTabModelDataDataOfferImages.fromJson(v));
      });
      offerImages = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['userId'] = userId;
    data['name'] = name;
    data['price'] = price;
    data['description'] = description;
    data['totalSold'] = totalSold;
    data['deliveryTime'] = deliveryTime;
    data['image'] = image;
    if (adOn != null) {
      final v = adOn;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['adOn'] = arr0;
    }
    data['isBoosted'] = isBoosted;
    data['boostTime'] = boostTime;
    data['created'] = created;
    data['modified'] = modified;
    data['isFavOffer'] = isFavOffer;
    data['rating'] = rating;
    if (offerImages != null) {
      final v = offerImages;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['offerImages'] = arr0;
    }
    return data;
  }
}

class OfferTabModelData {
/*
{
  "data": [
    {
      "id": 2,
      "userId": 2,
      "name": "Tiles Setup In Room",
      "price": 2000,
      "description": "Setting tiles in a room.",
      "totalSold": 1,
      "deliveryTime": 4,
      "image": "",
      "adOn": [
        {
          "price": "2000",
          "title": "Setting Tiles In Walls of Room",
          "workingDays": "2 Days"
        }
      ],
      "isBoosted": 0,
      "boostTime": 0,
      "created": 1738859997,
      "modified": 1742060161,
      "isFavOffer": 0,
      "rating": "0.0",
      "offerImages": [
        {
          "id": 5,
          "offerId": 2,
          "attachments": "https://app.superinstajobs.com/uploads/1738859997396.106.jpg",
          "created": 1738859997,
          "modified": 1738859997
        }
      ]
    }
  ],
  "pagination": {
    "currentPage": 1,
    "totalPage": 1,
    "totalRecord": 2,
    "limit": 10
  }
}
*/

  List<OfferTabModelDataData?>? data;
  OfferTabModelDataPagination? pagination;

  OfferTabModelData({
    this.data,
    this.pagination,
  });
  OfferTabModelData.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <OfferTabModelDataData>[];
      v.forEach((v) {
        arr0.add(OfferTabModelDataData.fromJson(v));
      });
      this.data = arr0;
    }
    pagination = (json['pagination'] != null) ? OfferTabModelDataPagination.fromJson(json['pagination']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    if (pagination != null) {
      data['pagination'] = pagination!.toJson();
    }
    return data;
  }
}

class OfferTabModel {
/*
{
  "success": true,
  "message": "All offer list",
  "status": 200,
  "data": {
    "data": [
      {
        "id": 2,
        "userId": 2,
        "name": "Tiles Setup In Room",
        "price": 2000,
        "description": "Setting tiles in a room.",
        "totalSold": 1,
        "deliveryTime": 4,
        "image": "",
        "adOn": [
          {
            "price": "2000",
            "title": "Setting Tiles In Walls of Room",
            "workingDays": "2 Days"
          }
        ],
        "isBoosted": 0,
        "boostTime": 0,
        "created": 1738859997,
        "modified": 1742060161,
        "isFavOffer": 0,
        "rating": "0.0",
        "offerImages": [
          {
            "id": 5,
            "offerId": 2,
            "attachments": "https://app.superinstajobs.com/uploads/1738859997396.106.jpg",
            "created": 1738859997,
            "modified": 1738859997
          }
        ]
      }
    ],
    "pagination": {
      "currentPage": 1,
      "totalPage": 1,
      "totalRecord": 2,
      "limit": 10
    }
  }
}
*/

  bool? success;
  String? message;
  int? status;
  OfferTabModelData? data;

  OfferTabModel({
    this.success,
    this.message,
    this.status,
    this.data,
  });
  OfferTabModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    status = json['status']?.toInt();
    data = (json['data'] != null) ? OfferTabModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    data['status'] = status;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
