///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class OfferDetailsModelDataAvgRating {
/*
{
  "communicationRating": "0.0",
  "attitudeRating": "0.0",
  "deliveryRating": "0.0"
}
*/

  String? communicationRating;
  String? attitudeRating;
  String? deliveryRating;

  OfferDetailsModelDataAvgRating({
    this.communicationRating,
    this.attitudeRating,
    this.deliveryRating,
  });
  OfferDetailsModelDataAvgRating.fromJson(Map<String, dynamic> json) {
    communicationRating = json['communicationRating']?.toString();
    attitudeRating = json['attitudeRating']?.toString();
    deliveryRating = json['deliveryRating']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['communicationRating'] = communicationRating;
    data['attitudeRating'] = attitudeRating;
    data['deliveryRating'] = deliveryRating;
    return data;
  }
}

class OfferDetailsModelDataOfferImages {
/*
{
  "id": 5,
  "offerId": 2,
  "attachments": "https://app.superinstajobs.com/uploads/1738859997396.106.jpg",
  "created": 1738859997,
  "modified": 1738859997
}
*/

  int? id;
  int? offerId;
  String? attachments;
  int? created;
  int? modified;

  OfferDetailsModelDataOfferImages({
    this.id,
    this.offerId,
    this.attachments,
    this.created,
    this.modified,
  });
  OfferDetailsModelDataOfferImages.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    offerId = json['offerId']?.toInt();
    attachments = json['attachments']?.toString();
    created = json['created']?.toInt();
    modified = json['modified']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['offerId'] = offerId;
    data['attachments'] = attachments;
    data['created'] = created;
    data['modified'] = modified;
    return data;
  }
}

class OfferDetailsModelDataUsers {
/*
{
  "id": 2,
  "name": "Jyoti Builders",
  "email": "jyoti@yopmail.com",
  "profile": "https://app.superinstajobs.com/uploads/1743437099493.0781.jpg"
}
*/

  int? id;
  String? name;
  String? email;
  String? profile;

  OfferDetailsModelDataUsers({
    this.id,
    this.name,
    this.email,
    this.profile,
  });
  OfferDetailsModelDataUsers.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    email = json['email']?.toString();
    profile = json['profile']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['email'] = email;
    data['profile'] = profile;
    return data;
  }
}

class OfferDetailsModelDataAdOn {
/*
{
  "price": "2000",
  "title": "Setting Tiles In Walls of Room",
  "workingDays": "2 Days"
}
*/

  String? price;
  String? title;
  String? workingDays;
  bool ? isSelected;

  OfferDetailsModelDataAdOn({
    this.price,
    this.title,
    this.workingDays,
    this.isSelected=false,
  });
  OfferDetailsModelDataAdOn.fromJson(Map<String, dynamic> json) {
    price = json['price']?.toString();
    isSelected = false;
    title = json['title']?.toString();
    workingDays = json['workingDays']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['isSelected'] = isSelected;
    data['price'] = price;
    data['title'] = title;
    data['workingDays'] = workingDays;
    return data;
  }
}

class OfferDetailsModelData {
/*
{
  "id": 2,
  "userId": 2,
  "name": "Tiles Setup In Room",
  "price": 2000,
  "description": "Setting tiles in a room.",
  "totalSold": 1,
  "deliveryTime": 4,
  "image": "",
  "adOn": [
    {
      "price": "2000",
      "title": "Setting Tiles In Walls of Room",
      "workingDays": "2 Days"
    }
  ],
  "isBoosted": 0,
  "boostTime": 0,
  "created": 1738859997,
  "modified": 1742060161,
  "isFavOffer": 0,
  "rating": "0.0",
  "users": {
    "id": 2,
    "name": "Jyoti Builders",
    "email": "jyoti@yopmail.com",
    "profile": "https://app.superinstajobs.com/uploads/1743437099493.0781.jpg"
  },
  "offerImages": [
    {
      "id": 5,
      "offerId": 2,
      "attachments": "https://app.superinstajobs.com/uploads/1738859997396.106.jpg",
      "created": 1738859997,
      "modified": 1738859997
    }
  ],
  "avgRating": {
    "communicationRating": "0.0",
    "attitudeRating": "0.0",
    "deliveryRating": "0.0"
  },
  "allRatings": [
    ""
  ]
}
*/

  int? id;
  int? userId;
  String? name;
  int? price;
  String? description;
  int? totalSold;
  int? deliveryTime;
  String? image;
  List<OfferDetailsModelDataAdOn?>? adOn;
  int? isBoosted;
  int? boostTime;
  int? created;
  int? modified;
  int? isFavOffer;
  String? rating;
  OfferDetailsModelDataUsers? users;
  List<OfferDetailsModelDataOfferImages?>? offerImages;
  OfferDetailsModelDataAvgRating? avgRating;
  List<String?>? allRatings;

  OfferDetailsModelData({
    this.id,
    this.userId,
    this.name,
    this.price,
    this.description,
    this.totalSold,
    this.deliveryTime,
    this.image,
    this.adOn,
    this.isBoosted,
    this.boostTime,
    this.created,
    this.modified,
    this.isFavOffer,
    this.rating,
    this.users,
    this.offerImages,
    this.avgRating,
    this.allRatings,
  });
  OfferDetailsModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    userId = json['userId']?.toInt();
    name = json['name']?.toString();
    price = json['price']?.toInt();
    description = json['description']?.toString();
    totalSold = json['totalSold']?.toInt();
    deliveryTime = json['deliveryTime']?.toInt();
    image = json['image']?.toString();
    if (json['adOn'] != null) {
      final v = json['adOn'];
      final arr0 = <OfferDetailsModelDataAdOn>[];
      v.forEach((v) {
        arr0.add(OfferDetailsModelDataAdOn.fromJson(v));
      });
      adOn = arr0;
    }
    isBoosted = json['isBoosted']?.toInt();
    boostTime = json['boostTime']?.toInt();
    created = json['created']?.toInt();
    modified = json['modified']?.toInt();
    isFavOffer = json['isFavOffer']?.toInt();
    rating = json['rating']?.toString();
    users = (json['users'] != null) ? OfferDetailsModelDataUsers.fromJson(json['users']) : null;
    if (json['offerImages'] != null) {
      final v = json['offerImages'];
      final arr0 = <OfferDetailsModelDataOfferImages>[];
      v.forEach((v) {
        arr0.add(OfferDetailsModelDataOfferImages.fromJson(v));
      });
      offerImages = arr0;
    }
    avgRating = (json['avgRating'] != null) ? OfferDetailsModelDataAvgRating.fromJson(json['avgRating']) : null;
    if (json['allRatings'] != null) {
      final v = json['allRatings'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      allRatings = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['userId'] = userId;
    data['name'] = name;
    data['price'] = price;
    data['description'] = description;
    data['totalSold'] = totalSold;
    data['deliveryTime'] = deliveryTime;
    data['image'] = image;
    if (adOn != null) {
      final v = adOn;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['adOn'] = arr0;
    }
    data['isBoosted'] = isBoosted;
    data['boostTime'] = boostTime;
    data['created'] = created;
    data['modified'] = modified;
    data['isFavOffer'] = isFavOffer;
    data['rating'] = rating;
    if (users != null) {
      data['users'] = users!.toJson();
    }
    if (offerImages != null) {
      final v = offerImages;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['offerImages'] = arr0;
    }
    if (avgRating != null) {
      data['avgRating'] = avgRating!.toJson();
    }
    if (allRatings != null) {
      final v = allRatings;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['allRatings'] = arr0;
    }
    return data;
  }
}

class OfferDetailsModel {
/*
{
  "success": true,
  "message": "Offer Details",
  "status": 200,
  "data": {
    "id": 2,
    "userId": 2,
    "name": "Tiles Setup In Room",
    "price": 2000,
    "description": "Setting tiles in a room.",
    "totalSold": 1,
    "deliveryTime": 4,
    "image": "",
    "adOn": [
      {
        "price": "2000",
        "title": "Setting Tiles In Walls of Room",
        "workingDays": "2 Days"
      }
    ],
    "isBoosted": 0,
    "boostTime": 0,
    "created": 1738859997,
    "modified": 1742060161,
    "isFavOffer": 0,
    "rating": "0.0",
    "users": {
      "id": 2,
      "name": "Jyoti Builders",
      "email": "jyoti@yopmail.com",
      "profile": "https://app.superinstajobs.com/uploads/1743437099493.0781.jpg"
    },
    "offerImages": [
      {
        "id": 5,
        "offerId": 2,
        "attachments": "https://app.superinstajobs.com/uploads/1738859997396.106.jpg",
        "created": 1738859997,
        "modified": 1738859997
      }
    ],
    "avgRating": {
      "communicationRating": "0.0",
      "attitudeRating": "0.0",
      "deliveryRating": "0.0"
    },
    "allRatings": [
      ""
    ]
  }
}
*/

  bool? success;
  String? message;
  int? status;
  OfferDetailsModelData? data;

  OfferDetailsModel({
    this.success,
    this.message,
    this.status,
    this.data,
  });
  OfferDetailsModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    status = json['status']?.toInt();
    data = (json['data'] != null) ? OfferDetailsModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    data['status'] = status;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
