///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PaymentReponseModelDataCard {
/*
{
  "first_6digits": "553188",
  "last_4digits": "2950",
  "issuer": "MASTERCARD  CREDIT",
  "country": "NG",
  "type": "MASTERCARD",
  "expiry": "09/31"
}
*/

  String? first_6digits;
  String? last_4digits;
  String? issuer;
  String? country;
  String? type;
  String? expiry;

  PaymentReponseModelDataCard({
    this.first_6digits,
    this.last_4digits,
    this.issuer,
    this.country,
    this.type,
    this.expiry,
  });
  PaymentReponseModelDataCard.fromJson(Map<String, dynamic> json) {
    first_6digits = json['first_6digits']?.toString();
    last_4digits = json['last_4digits']?.toString();
    issuer = json['issuer']?.toString();
    country = json['country']?.toString();
    type = json['type']?.toString();
    expiry = json['expiry']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['first_6digits'] = first_6digits;
    data['last_4digits'] = last_4digits;
    data['issuer'] = issuer;
    data['country'] = country;
    data['type'] = type;
    data['expiry'] = expiry;
    return data;
  }
}

class PaymentReponseModelDataCustomer {
/*
{
  "id": 3305429,
  "phone_number": "7888644412",
  "name": "krishan krishan 1732117560360",
  "email": "ravesb_f7fe70623bdb726edcbd_krishansokhal2000@gmail.com",
  "created_at": "2025-06-03T06:51:10.000Z"
}
*/

  int? id;
  String? phoneNumber;
  String? name;
  String? email;
  String? createdAt;

  PaymentReponseModelDataCustomer({
    this.id,
    this.phoneNumber,
    this.name,
    this.email,
    this.createdAt,
  });
  PaymentReponseModelDataCustomer.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    phoneNumber = json['phone_number']?.toString();
    name = json['name']?.toString();
    email = json['email']?.toString();
    createdAt = json['created_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['phone_number'] = phoneNumber;
    data['name'] = name;
    data['email'] = email;
    data['created_at'] = createdAt;
    return data;
  }
}

class PaymentReponseModelData {
/*
{
  "id": 9403786,
  "tx_ref": "TX-1749064861319",
  "flw_ref": "FLW-MOCK-ebba60725a945a34f0e121fedffc0a70",
  "device_fingerprint": "N/A",
  "amount": 100,
  "charged_amount": 100,
  "app_fee": 1.4,
  "merchant_fee": 0,
  "processor_response": "Please enter the OTP sent to your mobile number 080****** and email te**@rave**.com",
  "auth_model": "VBVSECURECODE",
  "currency": "NGN",
  "ip": "54.75.161.64",
  "narration": "CARD Transaction ",
  "status": "pending",
  "payment_type": "card",
  "plan": "",
  "fraud_status": "ok",
  "charge_type": "normal",
  "created_at": "2025-06-04T19:21:03.000Z",
  "account_id": 2564335,
  "customer": {
    "id": 3305429,
    "phone_number": "7888644412",
    "name": "krishan krishan 1732117560360",
    "email": "ravesb_f7fe70623bdb726edcbd_krishansokhal2000@gmail.com",
    "created_at": "2025-06-03T06:51:10.000Z"
  },
  "card": {
    "first_6digits": "553188",
    "last_4digits": "2950",
    "issuer": "MASTERCARD  CREDIT",
    "country": "NG",
    "type": "MASTERCARD",
    "expiry": "09/31"
  }
}
*/

  int? id;
  String? txRef;
  String? flwRef;
  String? deviceFingerprint;
  int? amount;
  int? chargedAmount;
  double? appFee;
  int? merchantFee;
  String? processorResponse;
  String? authModel;
  String? currency;
  String? ip;
  String? narration;
  String? status;
  String? paymentType;
  String? plan;
  String? fraudStatus;
  String? chargeType;
  String? createdAt;
  int? accountId;
  PaymentReponseModelDataCustomer? customer;
  PaymentReponseModelDataCard? card;

  PaymentReponseModelData({
    this.id,
    this.txRef,
    this.flwRef,
    this.deviceFingerprint,
    this.amount,
    this.chargedAmount,
    this.appFee,
    this.merchantFee,
    this.processorResponse,
    this.authModel,
    this.currency,
    this.ip,
    this.narration,
    this.status,
    this.paymentType,
    this.plan,
    this.fraudStatus,
    this.chargeType,
    this.createdAt,
    this.accountId,
    this.customer,
    this.card,
  });
  PaymentReponseModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    txRef = json['tx_ref']?.toString();
    flwRef = json['flw_ref']?.toString();
    deviceFingerprint = json['device_fingerprint']?.toString();
    amount = json['amount']?.toInt();
    chargedAmount = json['charged_amount']?.toInt();
    appFee = json['app_fee']?.toDouble();
    merchantFee = json['merchant_fee']?.toInt();
    processorResponse = json['processor_response']?.toString();
    authModel = json['auth_model']?.toString();
    currency = json['currency']?.toString();
    ip = json['ip']?.toString();
    narration = json['narration']?.toString();
    status = json['status']?.toString();
    paymentType = json['payment_type']?.toString();
    plan = json['plan']?.toString();
    fraudStatus = json['fraud_status']?.toString();
    chargeType = json['charge_type']?.toString();
    createdAt = json['created_at']?.toString();
    accountId = json['account_id']?.toInt();
    customer = (json['customer'] != null) ? PaymentReponseModelDataCustomer.fromJson(json['customer']) : null;
    card = (json['card'] != null) ? PaymentReponseModelDataCard.fromJson(json['card']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['tx_ref'] = txRef;
    data['flw_ref'] = flwRef;
    data['device_fingerprint'] = deviceFingerprint;
    data['amount'] = amount;
    data['charged_amount'] = chargedAmount;
    data['app_fee'] = appFee;
    data['merchant_fee'] = merchantFee;
    data['processor_response'] = processorResponse;
    data['auth_model'] = authModel;
    data['currency'] = currency;
    data['ip'] = ip;
    data['narration'] = narration;
    data['status'] = status;
    data['payment_type'] = paymentType;
    data['plan'] = plan;
    data['fraud_status'] = fraudStatus;
    data['charge_type'] = chargeType;
    data['created_at'] = createdAt;
    data['account_id'] = accountId;
    if (customer != null) {
      data['customer'] = customer!.toJson();
    }
    if (card != null) {
      data['card'] = card!.toJson();
    }
    return data;
  }
}

class PaymentReponseModel {
/*
{
  "success": true,
  "message": "Please enter the OTP sent to your mobile number 080****** and email te**@rave**.com",
  "status": 200,
  "data": {
    "id": 9403786,
    "tx_ref": "TX-1749064861319",
    "flw_ref": "FLW-MOCK-ebba60725a945a34f0e121fedffc0a70",
    "device_fingerprint": "N/A",
    "amount": 100,
    "charged_amount": 100,
    "app_fee": 1.4,
    "merchant_fee": 0,
    "processor_response": "Please enter the OTP sent to your mobile number 080****** and email te**@rave**.com",
    "auth_model": "VBVSECURECODE",
    "currency": "NGN",
    "ip": "54.75.161.64",
    "narration": "CARD Transaction ",
    "status": "pending",
    "payment_type": "card",
    "plan": "",
    "fraud_status": "ok",
    "charge_type": "normal",
    "created_at": "2025-06-04T19:21:03.000Z",
    "account_id": 2564335,
    "customer": {
      "id": 3305429,
      "phone_number": "7888644412",
      "name": "krishan krishan 1732117560360",
      "email": "ravesb_f7fe70623bdb726edcbd_krishansokhal2000@gmail.com",
      "created_at": "2025-06-03T06:51:10.000Z"
    },
    "card": {
      "first_6digits": "553188",
      "last_4digits": "2950",
      "issuer": "MASTERCARD  CREDIT",
      "country": "NG",
      "type": "MASTERCARD",
      "expiry": "09/31"
    }
  }
}
*/

  bool? success;
  String? message;
  int? status;
  PaymentReponseModelData? data;

  PaymentReponseModel({
    this.success,
    this.message,
    this.status,
    this.data,
  });
  PaymentReponseModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    status = json['status']?.toInt();
    data = (json['data'] != null) ? PaymentReponseModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    data['status'] = status;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
