///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ServicesUsersModelDataPagination {
/*
{
  "currentPage": 1,
  "totalPage": 1,
  "totalRecord": 2,
  "limit": 10
}
*/

  int? currentPage;
  int? totalPage;
  int? totalRecord;
  int? limit;

  ServicesUsersModelDataPagination({
    this.currentPage,
    this.totalPage,
    this.totalRecord,
    this.limit,
  });
  ServicesUsersModelDataPagination.fromJson(Map<String, dynamic> json) {
    currentPage = json['currentPage']?.toInt();
    totalPage = json['totalPage']?.toInt();
    totalRecord = json['totalRecord']?.toInt();
    limit = json['limit']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['currentPage'] = currentPage;
    data['totalPage'] = totalPage;
    data['totalRecord'] = totalRecord;
    data['limit'] = limit;
    return data;
  }
}

class ServicesUsersModelDataDataUsers {
/*
{
  "id": 16,
  "email": "xyz@gmail.com",
  "name": "sonal",
  "phone": "90909090",
  "userTypes": 1,
  "descriptions": "1212121",
  "totalJobs": 0,
  "totalHours": 0,
  "totalEarning": 0,
  "status": 0,
  "country": "tt",
  "state": "t",
  "city": "t",
  "street": "t",
  "latitude": 30.3456,
  "longitude": 74.23232,
  "profile": "",
  "boostTime": 0,
  "isBoosted": 0,
  "hourlyPrice": 0,
  "dailyPrice": 0,
  "favVendor": 0,
  "reviewsCount": 0,
  "lowestPrice": 0,
  "overallRating": "0.0"
}
*/

  int? id;
  String? email;
  String? name;
  String? phone;
  int? userTypes;
  String? descriptions;
  int? totalJobs;
  int? totalHours;
  int? totalEarning;
  int? status;
  String? country;
  String? state;
  String? city;
  String? street;
  double? latitude;
  double? longitude;
  String? profile;
  int? boostTime;
  int? isBoosted;
  int? hourlyPrice;
  int? dailyPrice;
  int? favVendor;
  int? reviewsCount;
  int? lowestPrice;
  String? overallRating;

  ServicesUsersModelDataDataUsers({
    this.id,
    this.email,
    this.name,
    this.phone,
    this.userTypes,
    this.descriptions,
    this.totalJobs,
    this.totalHours,
    this.totalEarning,
    this.status,
    this.country,
    this.state,
    this.city,
    this.street,
    this.latitude,
    this.longitude,
    this.profile,
    this.boostTime,
    this.isBoosted,
    this.hourlyPrice,
    this.dailyPrice,
    this.favVendor,
    this.reviewsCount,
    this.lowestPrice,
    this.overallRating,
  });
  ServicesUsersModelDataDataUsers.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    email = json['email']?.toString();
    name = json['name']?.toString();
    phone = json['phone']?.toString();
    userTypes = json['userTypes']?.toInt();
    descriptions = json['descriptions']?.toString();
    totalJobs = json['totalJobs']?.toInt();
    totalHours = json['totalHours']?.toInt();
    totalEarning = json['totalEarning']?.toInt();
    status = json['status']?.toInt();
    country = json['country']?.toString();
    state = json['state']?.toString();
    city = json['city']?.toString();
    street = json['street']?.toString();
    latitude = json['latitude']?.toDouble();
    longitude = json['longitude']?.toDouble();
    profile = json['profile']?.toString();
    boostTime = json['boostTime']?.toInt();
    isBoosted = json['isBoosted']?.toInt();
    hourlyPrice = json['hourlyPrice']?.toInt();
    dailyPrice = json['dailyPrice']?.toInt();
    favVendor = json['favVendor']?.toInt();
    reviewsCount = json['reviewsCount']?.toInt();
    lowestPrice = json['lowestPrice']?.toInt();
    overallRating = json['overallRating']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['email'] = email;
    data['name'] = name;
    data['phone'] = phone;
    data['userTypes'] = userTypes;
    data['descriptions'] = descriptions;
    data['totalJobs'] = totalJobs;
    data['totalHours'] = totalHours;
    data['totalEarning'] = totalEarning;
    data['status'] = status;
    data['country'] = country;
    data['state'] = state;
    data['city'] = city;
    data['street'] = street;
    data['latitude'] = latitude;
    data['longitude'] = longitude;
    data['profile'] = profile;
    data['boostTime'] = boostTime;
    data['isBoosted'] = isBoosted;
    data['hourlyPrice'] = hourlyPrice;
    data['dailyPrice'] = dailyPrice;
    data['favVendor'] = favVendor;
    data['reviewsCount'] = reviewsCount;
    data['lowestPrice'] = lowestPrice;
    data['overallRating'] = overallRating;
    return data;
  }
}

class ServicesUsersModelDataDataSubCategories {
/*
{
  "id": 8,
  "categoryId": 3,
  "name": "Frontend Developer",
  "image": "",
  "status": 0,
  "created": 0,
  "modified": 0
}
*/

  int? id;
  int? categoryId;
  String? name;
  String? image;
  int? status;
  int? created;
  int? modified;

  ServicesUsersModelDataDataSubCategories({
    this.id,
    this.categoryId,
    this.name,
    this.image,
    this.status,
    this.created,
    this.modified,
  });
  ServicesUsersModelDataDataSubCategories.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    categoryId = json['categoryId']?.toInt();
    name = json['name']?.toString();
    image = json['image']?.toString();
    status = json['status']?.toInt();
    created = json['created']?.toInt();
    modified = json['modified']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['categoryId'] = categoryId;
    data['name'] = name;
    data['image'] = image;
    data['status'] = status;
    data['created'] = created;
    data['modified'] = modified;
    return data;
  }
}

class ServicesUsersModelDataDataCategories {
/*
{
  "id": 3,
  "name": "IT & Web",
  "image": "https://app.superinstajobs.com/uploads/1722582629365.915.png",
  "status": 1,
  "isSubCategories": 1,
  "created": 0,
  "modified": 1722582629
}
*/

  int? id;
  String? name;
  String? image;
  int? status;
  int? isSubCategories;
  int? created;
  int? modified;

  ServicesUsersModelDataDataCategories({
    this.id,
    this.name,
    this.image,
    this.status,
    this.isSubCategories,
    this.created,
    this.modified,
  });
  ServicesUsersModelDataDataCategories.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    image = json['image']?.toString();
    status = json['status']?.toInt();
    isSubCategories = json['isSubCategories']?.toInt();
    created = json['created']?.toInt();
    modified = json['modified']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['image'] = image;
    data['status'] = status;
    data['isSubCategories'] = isSubCategories;
    data['created'] = created;
    data['modified'] = modified;
    return data;
  }
}

class ServicesUsersModelDataData {
/*
{
  "id": 11,
  "userId": 16,
  "categoryId": 3,
  "subCategoryId": "9,10,8",
  "created": 1745914306,
  "modified": 1745914306,
  "categories": {
    "id": 3,
    "name": "IT & Web",
    "image": "https://app.superinstajobs.com/uploads/1722582629365.915.png",
    "status": 1,
    "isSubCategories": 1,
    "created": 0,
    "modified": 1722582629
  },
  "subCategories": [
    {
      "id": 8,
      "categoryId": 3,
      "name": "Frontend Developer",
      "image": "",
      "status": 0,
      "created": 0,
      "modified": 0
    }
  ],
  "users": {
    "id": 16,
    "email": "xyz@gmail.com",
    "name": "sonal",
    "phone": "90909090",
    "userTypes": 1,
    "descriptions": "1212121",
    "totalJobs": 0,
    "totalHours": 0,
    "totalEarning": 0,
    "status": 0,
    "country": "tt",
    "state": "t",
    "city": "t",
    "street": "t",
    "latitude": 30.3456,
    "longitude": 74.23232,
    "profile": "",
    "boostTime": 0,
    "isBoosted": 0,
    "hourlyPrice": 0,
    "dailyPrice": 0,
    "favVendor": 0,
    "reviewsCount": 0,
    "lowestPrice": 0,
    "overallRating": "0.0"
  }
}
*/

  int? id;
  int? userId;
  int? categoryId;
  String? subCategoryId;
  int? created;
  int? modified;
  ServicesUsersModelDataDataCategories? categories;
  List<ServicesUsersModelDataDataSubCategories?>? subCategories;
  ServicesUsersModelDataDataUsers? users;

  ServicesUsersModelDataData({
    this.id,
    this.userId,
    this.categoryId,
    this.subCategoryId,
    this.created,
    this.modified,
    this.categories,
    this.subCategories,
    this.users,
  });
  ServicesUsersModelDataData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    userId = json['userId']?.toInt();
    categoryId = json['categoryId']?.toInt();
    subCategoryId = json['subCategoryId']?.toString();
    created = json['created']?.toInt();
    modified = json['modified']?.toInt();
    categories = (json['categories'] != null) ? ServicesUsersModelDataDataCategories.fromJson(json['categories']) : null;
    if (json['subCategories'] != null) {
      final v = json['subCategories'];
      final arr0 = <ServicesUsersModelDataDataSubCategories>[];
      v.forEach((v) {
        arr0.add(ServicesUsersModelDataDataSubCategories.fromJson(v));
      });
      subCategories = arr0;
    }
    users = (json['users'] != null) ? ServicesUsersModelDataDataUsers.fromJson(json['users']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['userId'] = userId;
    data['categoryId'] = categoryId;
    data['subCategoryId'] = subCategoryId;
    data['created'] = created;
    data['modified'] = modified;
    if (categories != null) {
      data['categories'] = categories!.toJson();
    }
    if (subCategories != null) {
      final v = subCategories;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['subCategories'] = arr0;
    }
    if (users != null) {
      data['users'] = users!.toJson();
    }
    return data;
  }
}

class ServicesUsersModelData {
/*
{
  "data": [
    {
      "id": 11,
      "userId": 16,
      "categoryId": 3,
      "subCategoryId": "9,10,8",
      "created": 1745914306,
      "modified": 1745914306,
      "categories": {
        "id": 3,
        "name": "IT & Web",
        "image": "https://app.superinstajobs.com/uploads/1722582629365.915.png",
        "status": 1,
        "isSubCategories": 1,
        "created": 0,
        "modified": 1722582629
      },
      "subCategories": [
        {
          "id": 8,
          "categoryId": 3,
          "name": "Frontend Developer",
          "image": "",
          "status": 0,
          "created": 0,
          "modified": 0
        }
      ],
      "users": {
        "id": 16,
        "email": "xyz@gmail.com",
        "name": "sonal",
        "phone": "90909090",
        "userTypes": 1,
        "descriptions": "1212121",
        "totalJobs": 0,
        "totalHours": 0,
        "totalEarning": 0,
        "status": 0,
        "country": "tt",
        "state": "t",
        "city": "t",
        "street": "t",
        "latitude": 30.3456,
        "longitude": 74.23232,
        "profile": "",
        "boostTime": 0,
        "isBoosted": 0,
        "hourlyPrice": 0,
        "dailyPrice": 0,
        "favVendor": 0,
        "reviewsCount": 0,
        "lowestPrice": 0,
        "overallRating": "0.0"
      }
    }
  ],
  "pagination": {
    "currentPage": 1,
    "totalPage": 1,
    "totalRecord": 2,
    "limit": 10
  }
}
*/

  List<ServicesUsersModelDataData?>? data;
  ServicesUsersModelDataPagination? pagination;

  ServicesUsersModelData({
    this.data,
    this.pagination,
  });
  ServicesUsersModelData.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <ServicesUsersModelDataData>[];
      v.forEach((v) {
        arr0.add(ServicesUsersModelDataData.fromJson(v));
      });
      this.data = arr0;
    }
    pagination = (json['pagination'] != null) ? ServicesUsersModelDataPagination.fromJson(json['pagination']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    if (pagination != null) {
      data['pagination'] = pagination!.toJson();
    }
    return data;
  }
}

class ServicesUsersModel {
/*
{
  "success": true,
  "message": "User listing",
  "status": 200,
  "data": {
    "data": [
      {
        "id": 11,
        "userId": 16,
        "categoryId": 3,
        "subCategoryId": "9,10,8",
        "created": 1745914306,
        "modified": 1745914306,
        "categories": {
          "id": 3,
          "name": "IT & Web",
          "image": "https://app.superinstajobs.com/uploads/1722582629365.915.png",
          "status": 1,
          "isSubCategories": 1,
          "created": 0,
          "modified": 1722582629
        },
        "subCategories": [
          {
            "id": 8,
            "categoryId": 3,
            "name": "Frontend Developer",
            "image": "",
            "status": 0,
            "created": 0,
            "modified": 0
          }
        ],
        "users": {
          "id": 16,
          "email": "xyz@gmail.com",
          "name": "sonal",
          "phone": "90909090",
          "userTypes": 1,
          "descriptions": "1212121",
          "totalJobs": 0,
          "totalHours": 0,
          "totalEarning": 0,
          "status": 0,
          "country": "tt",
          "state": "t",
          "city": "t",
          "street": "t",
          "latitude": 30.3456,
          "longitude": 74.23232,
          "profile": "",
          "boostTime": 0,
          "isBoosted": 0,
          "hourlyPrice": 0,
          "dailyPrice": 0,
          "favVendor": 0,
          "reviewsCount": 0,
          "lowestPrice": 0,
          "overallRating": "0.0"
        }
      }
    ],
    "pagination": {
      "currentPage": 1,
      "totalPage": 1,
      "totalRecord": 2,
      "limit": 10
    }
  }
}
*/

  bool? success;
  String? message;
  int? status;
  ServicesUsersModelData? data;

  ServicesUsersModel({
    this.success,
    this.message,
    this.status,
    this.data,
  });
  ServicesUsersModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    status = json['status']?.toInt();
    data = (json['data'] != null) ? ServicesUsersModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    data['status'] = status;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
