///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SubCategoryModelDataPagination {
/*
{
  "currentPage": 1,
  "totalPage": 1,
  "totalRecord": 4,
  "limit": 10
}
*/

  int? currentPage;
  int? totalPage;
  int? totalRecord;
  int? limit;

  SubCategoryModelDataPagination({
    this.currentPage,
    this.totalPage,
    this.totalRecord,
    this.limit,
  });
  SubCategoryModelDataPagination.fromJson(Map<String, dynamic> json) {
    currentPage = json['currentPage']?.toInt();
    totalPage = json['totalPage']?.toInt();
    totalRecord = json['totalRecord']?.toInt();
    limit = json['limit']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['currentPage'] = currentPage;
    data['totalPage'] = totalPage;
    data['totalRecord'] = totalRecord;
    data['limit'] = limit;
    return data;
  }
}

class SubCategoryModelDataSubCategories {
/*
{
  "id": 4,
  "categoryId": 1,
  "name": "Painter",
  "image": "",
  "status": 0,
  "created": 0,
  "modified": 0,
  "totalUsers": 3
}
*/

  int? id;
  int? categoryId;
  String? name;
  String? image;
  int? status;
  int? created;
  int? modified;
  int? totalUsers;
  bool ?isSelected ;

  SubCategoryModelDataSubCategories({
    this.id,
    this.categoryId,
    this.name,
    this.image,
    this.status,
    this.created,
    this.modified,
    this.totalUsers,
    this.isSelected,
  });
  SubCategoryModelDataSubCategories.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    isSelected = false;
    categoryId = json['categoryId']?.toInt();
    name = json['name']?.toString();
    image = json['image']?.toString();
    status = json['status']?.toInt();
    created = json['created']?.toInt();
    modified = json['modified']?.toInt();
    totalUsers = json['totalUsers']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['isSelected'] = isSelected;
    data['categoryId'] = categoryId;
    data['name'] = name;
    data['image'] = image;
    data['status'] = status;
    data['created'] = created;
    data['modified'] = modified;
    data['totalUsers'] = totalUsers;
    return data;
  }
}

class SubCategoryModelData {
/*
{
  "subCategories": [
    {
      "id": 4,
      "categoryId": 1,
      "name": "Painter",
      "image": "",
      "status": 0,
      "created": 0,
      "modified": 0,
      "totalUsers": 3
    }
  ],
  "pagination": {
    "currentPage": 1,
    "totalPage": 1,
    "totalRecord": 4,
    "limit": 10
  }
}
*/

  List<SubCategoryModelDataSubCategories?>? subCategories;
  SubCategoryModelDataPagination? pagination;

  SubCategoryModelData({
    this.subCategories,
    this.pagination,
  });
  SubCategoryModelData.fromJson(Map<String, dynamic> json) {
    if (json['subCategories'] != null) {
      final v = json['subCategories'];
      final arr0 = <SubCategoryModelDataSubCategories>[];
      v.forEach((v) {
        arr0.add(SubCategoryModelDataSubCategories.fromJson(v));
      });
      subCategories = arr0;
    }
    pagination = (json['pagination'] != null) ? SubCategoryModelDataPagination.fromJson(json['pagination']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (subCategories != null) {
      final v = subCategories;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['subCategories'] = arr0;
    }
    if (pagination != null) {
      data['pagination'] = pagination!.toJson();
    }
    return data;
  }
}

class SubCategoryModel {
/*
{
  "success": true,
  "message": "Sub-categories listing",
  "status": 200,
  "data": {
    "subCategories": [
      {
        "id": 4,
        "categoryId": 1,
        "name": "Painter",
        "image": "",
        "status": 0,
        "created": 0,
        "modified": 0,
        "totalUsers": 3
      }
    ],
    "pagination": {
      "currentPage": 1,
      "totalPage": 1,
      "totalRecord": 4,
      "limit": 10
    }
  }
}
*/

  bool? success;
  String? message;
  int? status;
  SubCategoryModelData? data;

  SubCategoryModel({
    this.success,
    this.message,
    this.status,
    this.data,
  });
  SubCategoryModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    status = json['status']?.toInt();
    data = (json['data'] != null) ? SubCategoryModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    data['status'] = status;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
