///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TagsModelDataPagination {
/*
{
  "currentPage": 1,
  "totalPage": 1,
  "totalRecord": 2,
  "limit": 10
}
*/

  int? currentPage;
  int? totalPage;
  int? totalRecord;
  int? limit;

  TagsModelDataPagination({
    this.currentPage,
    this.totalPage,
    this.totalRecord,
    this.limit,
  });
  TagsModelDataPagination.fromJson(Map<String, dynamic> json) {
    currentPage = json['currentPage']?.toInt();
    totalPage = json['totalPage']?.toInt();
    totalRecord = json['totalRecord']?.toInt();
    limit = json['limit']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['currentPage'] = currentPage;
    data['totalPage'] = totalPage;
    data['totalRecord'] = totalRecord;
    data['limit'] = limit;
    return data;
  }
}

class TagsModelDataDataCategories {
/*
{
  "id": 3,
  "name": "IT & Web",
  "image": "https://app.superinstajobs.com/uploads/1722582629365.915.png",
  "status": 1,
  "isSubCategories": 1,
  "created": 0,
  "modified": 1722582629
}
*/

  int? id;
  String? name;
  String? image;
  int? status;
  int? isSubCategories;
  int? created;
  int? modified;

  TagsModelDataDataCategories({
    this.id,
    this.name,
    this.image,
    this.status,
    this.isSubCategories,
    this.created,
    this.modified,
  });
  TagsModelDataDataCategories.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    image = json['image']?.toString();
    status = json['status']?.toInt();
    isSubCategories = json['isSubCategories']?.toInt();
    created = json['created']?.toInt();
    modified = json['modified']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['image'] = image;
    data['status'] = status;
    data['isSubCategories'] = isSubCategories;
    data['created'] = created;
    data['modified'] = modified;
    return data;
  }
}

class TagsModelDataData {
/*
{
  "id": 10,
  "categoryId": 3,
  "name": "Websiter Development",
  "status": 1,
  "created": 1738862361,
  "modified": 1738862361,
  "categories": {
    "id": 3,
    "name": "IT & Web",
    "image": "https://app.superinstajobs.com/uploads/1722582629365.915.png",
    "status": 1,
    "isSubCategories": 1,
    "created": 0,
    "modified": 1722582629
  }
}
*/

  int? id;
  int? categoryId;
  String? name;
  int? status;
  int? created;
  int? modified;
  bool? isSelected;
  TagsModelDataDataCategories? categories;

  TagsModelDataData({
    this.id,
    this.categoryId,
    this.name,
    this.status,
    this.created,
    this.modified,
    this.categories,
    this.isSelected,
  });
  TagsModelDataData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    isSelected = false;
    categoryId = json['categoryId']?.toInt();
    name = json['name']?.toString();
    status = json['status']?.toInt();
    created = json['created']?.toInt();
    modified = json['modified']?.toInt();
    categories = (json['categories'] != null) ? TagsModelDataDataCategories.fromJson(json['categories']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['isSelected'] = isSelected;
    data['categoryId'] = categoryId;
    data['name'] = name;
    data['status'] = status;
    data['created'] = created;
    data['modified'] = modified;
    if (categories != null) {
      data['categories'] = categories!.toJson();
    }
    return data;
  }
}

class TagsModelData {
/*
{
  "data": [
    {
      "id": 10,
      "categoryId": 3,
      "name": "Websiter Development",
      "status": 1,
      "created": 1738862361,
      "modified": 1738862361,
      "categories": {
        "id": 3,
        "name": "IT & Web",
        "image": "https://app.superinstajobs.com/uploads/1722582629365.915.png",
        "status": 1,
        "isSubCategories": 1,
        "created": 0,
        "modified": 1722582629
      }
    }
  ],
  "pagination": {
    "currentPage": 1,
    "totalPage": 1,
    "totalRecord": 2,
    "limit": 10
  }
}
*/

  List<TagsModelDataData?>? data;
  TagsModelDataPagination? pagination;

  TagsModelData({
    this.data,
    this.pagination,
  });
  TagsModelData.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <TagsModelDataData>[];
      v.forEach((v) {
        arr0.add(TagsModelDataData.fromJson(v));
      });
      this.data = arr0;
    }
    pagination = (json['pagination'] != null) ? TagsModelDataPagination.fromJson(json['pagination']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    if (pagination != null) {
      data['pagination'] = pagination!.toJson();
    }
    return data;
  }
}

class TagsModel {
/*
{
  "success": true,
  "message": "Tag list",
  "status": 200,
  "data": {
    "data": [
      {
        "id": 10,
        "categoryId": 3,
        "name": "Websiter Development",
        "status": 1,
        "created": 1738862361,
        "modified": 1738862361,
        "categories": {
          "id": 3,
          "name": "IT & Web",
          "image": "https://app.superinstajobs.com/uploads/1722582629365.915.png",
          "status": 1,
          "isSubCategories": 1,
          "created": 0,
          "modified": 1722582629
        }
      }
    ],
    "pagination": {
      "currentPage": 1,
      "totalPage": 1,
      "totalRecord": 2,
      "limit": 10
    }
  }
}
*/

  bool? success;
  String? message;
  int? status;
  TagsModelData? data;

  TagsModel({
    this.success,
    this.message,
    this.status,
    this.data,
  });
  TagsModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    status = json['status']?.toInt();
    data = (json['data'] != null) ? TagsModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    data['status'] = status;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
