///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class VendorDetailsModelDataUserInfoRating {
/*
{
  "overallRating": "0.0"
}
*/

  String? overallRating;

  VendorDetailsModelDataUserInfoRating({
    this.overallRating,
  });
  VendorDetailsModelDataUserInfoRating.fromJson(Map<String, dynamic> json) {
    overallRating = json['overallRating']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['overallRating'] = overallRating;
    return data;
  }
}

class VendorDetailsModelDataUserInfoNotifications {
/*
{
  "userId": "2",
  "newOfferUpload": 1,
  "likeAndComment": 1,
  "directMessage": 1,
  "pauseAll": 0
}
*/

  String? userId;
  int? newOfferUpload;
  int? likeAndComment;
  int? directMessage;
  int? pauseAll;

  VendorDetailsModelDataUserInfoNotifications({
    this.userId,
    this.newOfferUpload,
    this.likeAndComment,
    this.directMessage,
    this.pauseAll,
  });
  VendorDetailsModelDataUserInfoNotifications.fromJson(Map<String, dynamic> json) {
    userId = json['userId']?.toString();
    newOfferUpload = json['newOfferUpload']?.toInt();
    likeAndComment = json['likeAndComment']?.toInt();
    directMessage = json['directMessage']?.toInt();
    pauseAll = json['pauseAll']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['userId'] = userId;
    data['newOfferUpload'] = newOfferUpload;
    data['likeAndComment'] = likeAndComment;
    data['directMessage'] = directMessage;
    data['pauseAll'] = pauseAll;
    return data;
  }
}

class VendorDetailsModelDataUserInfoWalletInfo {
/*
{
  "id": 2,
  "userId": 2,
  "balance": 4659,
  "currency": "NGN",
  "created": 1738858266,
  "modified": 1743506880
}
*/

  int? id;
  int? userId;
  int? balance;
  String? currency;
  int? created;
  int? modified;

  VendorDetailsModelDataUserInfoWalletInfo({
    this.id,
    this.userId,
    this.balance,
    this.currency,
    this.created,
    this.modified,
  });
  VendorDetailsModelDataUserInfoWalletInfo.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    userId = json['userId']?.toInt();
    balance = json['balance']?.toInt();
    currency = json['currency']?.toString();
    created = json['created']?.toInt();
    modified = json['modified']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['userId'] = userId;
    data['balance'] = balance;
    data['currency'] = currency;
    data['created'] = created;
    data['modified'] = modified;
    return data;
  }
}

class VendorDetailsModelDataUserInfoCategorySubCategory {
/*
{
  "subCategoryId": 4,
  "name": "Painter",
  "image": ""
}
*/

  int? subCategoryId;
  String? name;
  String? image;

  VendorDetailsModelDataUserInfoCategorySubCategory({
    this.subCategoryId,
    this.name,
    this.image,
  });
  VendorDetailsModelDataUserInfoCategorySubCategory.fromJson(Map<String, dynamic> json) {
    subCategoryId = json['subCategoryId']?.toInt();
    name = json['name']?.toString();
    image = json['image']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['subCategoryId'] = subCategoryId;
    data['name'] = name;
    data['image'] = image;
    return data;
  }
}

class VendorDetailsModelDataUserInfoCategory {
/*
{
  "categoryId": 1,
  "categoryName": "Builders",
  "categoryImage": "https://app.superinstajobs.com/uploads/1722582520107.6833.png",
  "subCategory": [
    {
      "subCategoryId": 4,
      "name": "Painter",
      "image": ""
    }
  ]
}
*/

  int? categoryId;
  String? categoryName;
  String? categoryImage;
  List<VendorDetailsModelDataUserInfoCategorySubCategory?>? subCategory;

  VendorDetailsModelDataUserInfoCategory({
    this.categoryId,
    this.categoryName,
    this.categoryImage,
    this.subCategory,
  });
  VendorDetailsModelDataUserInfoCategory.fromJson(Map<String, dynamic> json) {
    categoryId = json['categoryId']?.toInt();
    categoryName = json['categoryName']?.toString();
    categoryImage = json['categoryImage']?.toString();
    if (json['subCategory'] != null) {
      final v = json['subCategory'];
      final arr0 = <VendorDetailsModelDataUserInfoCategorySubCategory>[];
      v.forEach((v) {
        arr0.add(VendorDetailsModelDataUserInfoCategorySubCategory.fromJson(v));
      });
      subCategory = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['categoryId'] = categoryId;
    data['categoryName'] = categoryName;
    data['categoryImage'] = categoryImage;
    if (subCategory != null) {
      final v = subCategory;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['subCategory'] = arr0;
    }
    return data;
  }
}

class VendorDetailsModelDataUserInfoAttachments {
/*
{
  "id": 3,
  "userId": 2,
  "type": 1,
  "attachments": "https://app.superinstajobs.com/uploads/1738858282015.776.jpg",
  "expireDate": 1740759080,
  "identifyId": "Doc1738858281454.jpg",
  "status": 1,
  "created": 1738858282,
  "modified": 1738858282
}
*/

  int? id;
  int? userId;
  int? type;
  String? attachments;
  int? expireDate;
  String? identifyId;
  int? status;
  int? created;
  int? modified;

  VendorDetailsModelDataUserInfoAttachments({
    this.id,
    this.userId,
    this.type,
    this.attachments,
    this.expireDate,
    this.identifyId,
    this.status,
    this.created,
    this.modified,
  });
  VendorDetailsModelDataUserInfoAttachments.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    userId = json['userId']?.toInt();
    type = json['type']?.toInt();
    attachments = json['attachments']?.toString();
    expireDate = json['expireDate']?.toInt();
    identifyId = json['identifyId']?.toString();
    status = json['status']?.toInt();
    created = json['created']?.toInt();
    modified = json['modified']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['userId'] = userId;
    data['type'] = type;
    data['attachments'] = attachments;
    data['expireDate'] = expireDate;
    data['identifyId'] = identifyId;
    data['status'] = status;
    data['created'] = created;
    data['modified'] = modified;
    return data;
  }
}

class VendorDetailsModelDataUserInfoRemainBoostedTime {
/*
{
  "daysDifference": 30,
  "hoursDifference": 0,
  "minutesDifference": 0,
  "secondsDifference": 0
}
*/

  int? daysDifference;
  int? hoursDifference;
  int? minutesDifference;
  int? secondsDifference;

  VendorDetailsModelDataUserInfoRemainBoostedTime({
    this.daysDifference,
    this.hoursDifference,
    this.minutesDifference,
    this.secondsDifference,
  });
  VendorDetailsModelDataUserInfoRemainBoostedTime.fromJson(Map<String, dynamic> json) {
    daysDifference = json['daysDifference']?.toInt();
    hoursDifference = json['hoursDifference']?.toInt();
    minutesDifference = json['minutesDifference']?.toInt();
    secondsDifference = json['secondsDifference']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['daysDifference'] = daysDifference;
    data['hoursDifference'] = hoursDifference;
    data['minutesDifference'] = minutesDifference;
    data['secondsDifference'] = secondsDifference;
    return data;
  }
}

class VendorDetailsModelDataUserInfoWorkingHours {
/*
{
  "friday": "10:00 - 18:00",
  "monday": "10:00 - 18:00",
  "sunday": "10:00 - 18:00",
  "tuesday": "00:00 - 00:00",
  "saturday": "10:00 - 18:00",
  "thursday": "00:00 - 00:00",
  "wednesday": "10:00 - 18:00"
}
*/

  String? friday;
  String? monday;
  String? sunday;
  String? tuesday;
  String? saturday;
  String? thursday;
  String? wednesday;

  VendorDetailsModelDataUserInfoWorkingHours({
    this.friday,
    this.monday,
    this.sunday,
    this.tuesday,
    this.saturday,
    this.thursday,
    this.wednesday,
  });
  VendorDetailsModelDataUserInfoWorkingHours.fromJson(Map<String, dynamic> json) {
    friday = json['friday']?.toString();
    monday = json['monday']?.toString();
    sunday = json['sunday']?.toString();
    tuesday = json['tuesday']?.toString();
    saturday = json['saturday']?.toString();
    thursday = json['thursday']?.toString();
    wednesday = json['wednesday']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['friday'] = friday;
    data['monday'] = monday;
    data['sunday'] = sunday;
    data['tuesday'] = tuesday;
    data['saturday'] = saturday;
    data['thursday'] = thursday;
    data['wednesday'] = wednesday;
    return data;
  }
}

class VendorDetailsModelDataUserInfo {
/*
{
  "id": 2,
  "email": "jyoti@yopmail.com",
  "name": "Jyoti Builders",
  "phone": "7888644412",
  "userTypes": 1,
  "descriptions": "Testing apps with different account",
  "totalJobs": 0,
  "totalHours": 0,
  "totalEarning": 0,
  "status": 1,
  "country": "India",
  "state": "Chandigarh",
  "city": "Chandigarh",
  "street": "Chandigarh Station FOB,  Daria",
  "latitude": 30.701536,
  "longitude": 76.82175,
  "isEmailVerify": 0,
  "isPhoneVerify": 0,
  "profile": "https://app.superinstajobs.com/uploads/1743437099493.0781.jpg",
  "boostTime": 1745067877,
  "isBoosted": 1,
  "isBlock": 0,
  "hourlyPrice": 10,
  "dailyPrice": 100,
  "workingHours": {
    "friday": "10:00 - 18:00",
    "monday": "10:00 - 18:00",
    "sunday": "10:00 - 18:00",
    "tuesday": "00:00 - 00:00",
    "saturday": "10:00 - 18:00",
    "thursday": "00:00 - 00:00",
    "wednesday": "10:00 - 18:00"
  },
  "favVendor": 1,
  "isBankLinked": 0,
  "remainBoostedTime": {
    "daysDifference": 30,
    "hoursDifference": 0,
    "minutesDifference": 0,
    "secondsDifference": 0
  },
  "attachments": [
    {
      "id": 3,
      "userId": 2,
      "type": 1,
      "attachments": "https://app.superinstajobs.com/uploads/1738858282015.776.jpg",
      "expireDate": 1740759080,
      "identifyId": "Doc1738858281454.jpg",
      "status": 1,
      "created": 1738858282,
      "modified": 1738858282
    }
  ],
  "category": [
    {
      "categoryId": 1,
      "categoryName": "Builders",
      "categoryImage": "https://app.superinstajobs.com/uploads/1722582520107.6833.png",
      "subCategory": [
        {
          "subCategoryId": 4,
          "name": "Painter",
          "image": ""
        }
      ]
    }
  ],
  "walletInfo": {
    "id": 2,
    "userId": 2,
    "balance": 4659,
    "currency": "NGN",
    "created": 1738858266,
    "modified": 1743506880
  },
  "notifications": {
    "userId": "2",
    "newOfferUpload": 1,
    "likeAndComment": 1,
    "directMessage": 1,
    "pauseAll": 0
  },
  "lowestPrice": 2000,
  "rating": {
    "overallRating": "0.0"
  },
  "allRatings": [
    ""
  ],
  "totalJobComplete": 0,
  "totalAmountEarned": 14,
  "totalOfferPurchased": 0,
  "totalOfferSale": 0,
  "totalJobPosted": 0,
  "totalAmountSpend": 4000
}
*/

  int? id;
  String? email;
  String? name;
  String? phone;
  int? userTypes;
  String? descriptions;
  int? totalJobs;
  int? totalHours;
  int? totalEarning;
  int? status;
  String? country;
  String? state;
  String? city;
  String? street;
  double? latitude;
  double? longitude;
  int? isEmailVerify;
  int? isPhoneVerify;
  String? profile;
  int? boostTime;
  int? isBoosted;
  int? isBlock;
  int? hourlyPrice;
  int? dailyPrice;
  VendorDetailsModelDataUserInfoWorkingHours? workingHours;
  int? favVendor;
  int? isBankLinked;
  VendorDetailsModelDataUserInfoRemainBoostedTime? remainBoostedTime;
  List<VendorDetailsModelDataUserInfoAttachments?>? attachments;
  List<VendorDetailsModelDataUserInfoCategory?>? category;
  VendorDetailsModelDataUserInfoWalletInfo? walletInfo;
  VendorDetailsModelDataUserInfoNotifications? notifications;
  int? lowestPrice;
  VendorDetailsModelDataUserInfoRating? rating;
  List<String?>? allRatings;
  int? totalJobComplete;
  int? totalAmountEarned;
  int? totalOfferPurchased;
  int? totalOfferSale;
  int? totalJobPosted;
  int? totalAmountSpend;

  VendorDetailsModelDataUserInfo({
    this.id,
    this.email,
    this.name,
    this.phone,
    this.userTypes,
    this.descriptions,
    this.totalJobs,
    this.totalHours,
    this.totalEarning,
    this.status,
    this.country,
    this.state,
    this.city,
    this.street,
    this.latitude,
    this.longitude,
    this.isEmailVerify,
    this.isPhoneVerify,
    this.profile,
    this.boostTime,
    this.isBoosted,
    this.isBlock,
    this.hourlyPrice,
    this.dailyPrice,
    this.workingHours,
    this.favVendor,
    this.isBankLinked,
    this.remainBoostedTime,
    this.attachments,
    this.category,
    this.walletInfo,
    this.notifications,
    this.lowestPrice,
    this.rating,
    this.allRatings,
    this.totalJobComplete,
    this.totalAmountEarned,
    this.totalOfferPurchased,
    this.totalOfferSale,
    this.totalJobPosted,
    this.totalAmountSpend,
  });
  VendorDetailsModelDataUserInfo.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    email = json['email']?.toString();
    name = json['name']?.toString();
    phone = json['phone']?.toString();
    userTypes = json['userTypes']?.toInt();
    descriptions = json['descriptions']?.toString();
    totalJobs = json['totalJobs']?.toInt();
    totalHours = json['totalHours']?.toInt();
    totalEarning = json['totalEarning']?.toInt();
    status = json['status']?.toInt();
    country = json['country']?.toString();
    state = json['state']?.toString();
    city = json['city']?.toString();
    street = json['street']?.toString();
    latitude = json['latitude']?.toDouble();
    longitude = json['longitude']?.toDouble();
    isEmailVerify = json['isEmailVerify']?.toInt();
    isPhoneVerify = json['isPhoneVerify']?.toInt();
    profile = json['profile']?.toString();
    boostTime = json['boostTime']?.toInt();
    isBoosted = json['isBoosted']?.toInt();
    isBlock = json['isBlock']?.toInt();
    hourlyPrice = json['hourlyPrice']?.toInt();
    dailyPrice = json['dailyPrice']?.toInt();
    workingHours = (json['workingHours'] != null) ? VendorDetailsModelDataUserInfoWorkingHours.fromJson(json['workingHours']) : null;
    favVendor = json['favVendor']?.toInt();
    isBankLinked = json['isBankLinked']?.toInt();
    remainBoostedTime = (json['remainBoostedTime'] != null) ? VendorDetailsModelDataUserInfoRemainBoostedTime.fromJson(json['remainBoostedTime']) : null;
    if (json['attachments'] != null) {
      final v = json['attachments'];
      final arr0 = <VendorDetailsModelDataUserInfoAttachments>[];
      v.forEach((v) {
        arr0.add(VendorDetailsModelDataUserInfoAttachments.fromJson(v));
      });
      attachments = arr0;
    }
    if (json['category'] != null) {
      final v = json['category'];
      final arr0 = <VendorDetailsModelDataUserInfoCategory>[];
      v.forEach((v) {
        arr0.add(VendorDetailsModelDataUserInfoCategory.fromJson(v));
      });
      category = arr0;
    }
    walletInfo = (json['walletInfo'] != null) ? VendorDetailsModelDataUserInfoWalletInfo.fromJson(json['walletInfo']) : null;
    notifications = (json['notifications'] != null) ? VendorDetailsModelDataUserInfoNotifications.fromJson(json['notifications']) : null;
    lowestPrice = json['lowestPrice']?.toInt();
    rating = (json['rating'] != null) ? VendorDetailsModelDataUserInfoRating.fromJson(json['rating']) : null;
    if (json['allRatings'] != null) {
      final v = json['allRatings'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      allRatings = arr0;
    }
    totalJobComplete = json['totalJobComplete']?.toInt();
    totalAmountEarned = json['totalAmountEarned']?.toInt();
    totalOfferPurchased = json['totalOfferPurchased']?.toInt();
    totalOfferSale = json['totalOfferSale']?.toInt();
    totalJobPosted = json['totalJobPosted']?.toInt();
    totalAmountSpend = json['totalAmountSpend']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['email'] = email;
    data['name'] = name;
    data['phone'] = phone;
    data['userTypes'] = userTypes;
    data['descriptions'] = descriptions;
    data['totalJobs'] = totalJobs;
    data['totalHours'] = totalHours;
    data['totalEarning'] = totalEarning;
    data['status'] = status;
    data['country'] = country;
    data['state'] = state;
    data['city'] = city;
    data['street'] = street;
    data['latitude'] = latitude;
    data['longitude'] = longitude;
    data['isEmailVerify'] = isEmailVerify;
    data['isPhoneVerify'] = isPhoneVerify;
    data['profile'] = profile;
    data['boostTime'] = boostTime;
    data['isBoosted'] = isBoosted;
    data['isBlock'] = isBlock;
    data['hourlyPrice'] = hourlyPrice;
    data['dailyPrice'] = dailyPrice;
    if (workingHours != null) {
      data['workingHours'] = workingHours!.toJson();
    }
    data['favVendor'] = favVendor;
    data['isBankLinked'] = isBankLinked;
    if (remainBoostedTime != null) {
      data['remainBoostedTime'] = remainBoostedTime!.toJson();
    }
    if (attachments != null) {
      final v = attachments;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['attachments'] = arr0;
    }
    if (category != null) {
      final v = category;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['category'] = arr0;
    }
    if (walletInfo != null) {
      data['walletInfo'] = walletInfo!.toJson();
    }
    if (notifications != null) {
      data['notifications'] = notifications!.toJson();
    }
    data['lowestPrice'] = lowestPrice;
    if (rating != null) {
      data['rating'] = rating!.toJson();
    }
    if (allRatings != null) {
      final v = allRatings;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['allRatings'] = arr0;
    }
    data['totalJobComplete'] = totalJobComplete;
    data['totalAmountEarned'] = totalAmountEarned;
    data['totalOfferPurchased'] = totalOfferPurchased;
    data['totalOfferSale'] = totalOfferSale;
    data['totalJobPosted'] = totalJobPosted;
    data['totalAmountSpend'] = totalAmountSpend;
    return data;
  }
}

class VendorDetailsModelData {
/*
{
  "userInfo": {
    "id": 2,
    "email": "jyoti@yopmail.com",
    "name": "Jyoti Builders",
    "phone": "7888644412",
    "userTypes": 1,
    "descriptions": "Testing apps with different account",
    "totalJobs": 0,
    "totalHours": 0,
    "totalEarning": 0,
    "status": 1,
    "country": "India",
    "state": "Chandigarh",
    "city": "Chandigarh",
    "street": "Chandigarh Station FOB,  Daria",
    "latitude": 30.701536,
    "longitude": 76.82175,
    "isEmailVerify": 0,
    "isPhoneVerify": 0,
    "profile": "https://app.superinstajobs.com/uploads/1743437099493.0781.jpg",
    "boostTime": 1745067877,
    "isBoosted": 1,
    "isBlock": 0,
    "hourlyPrice": 10,
    "dailyPrice": 100,
    "workingHours": {
      "friday": "10:00 - 18:00",
      "monday": "10:00 - 18:00",
      "sunday": "10:00 - 18:00",
      "tuesday": "00:00 - 00:00",
      "saturday": "10:00 - 18:00",
      "thursday": "00:00 - 00:00",
      "wednesday": "10:00 - 18:00"
    },
    "favVendor": 1,
    "isBankLinked": 0,
    "remainBoostedTime": {
      "daysDifference": 30,
      "hoursDifference": 0,
      "minutesDifference": 0,
      "secondsDifference": 0
    },
    "attachments": [
      {
        "id": 3,
        "userId": 2,
        "type": 1,
        "attachments": "https://app.superinstajobs.com/uploads/1738858282015.776.jpg",
        "expireDate": 1740759080,
        "identifyId": "Doc1738858281454.jpg",
        "status": 1,
        "created": 1738858282,
        "modified": 1738858282
      }
    ],
    "category": [
      {
        "categoryId": 1,
        "categoryName": "Builders",
        "categoryImage": "https://app.superinstajobs.com/uploads/1722582520107.6833.png",
        "subCategory": [
          {
            "subCategoryId": 4,
            "name": "Painter",
            "image": ""
          }
        ]
      }
    ],
    "walletInfo": {
      "id": 2,
      "userId": 2,
      "balance": 4659,
      "currency": "NGN",
      "created": 1738858266,
      "modified": 1743506880
    },
    "notifications": {
      "userId": "2",
      "newOfferUpload": 1,
      "likeAndComment": 1,
      "directMessage": 1,
      "pauseAll": 0
    },
    "lowestPrice": 2000,
    "rating": {
      "overallRating": "0.0"
    },
    "allRatings": [
      ""
    ],
    "totalJobComplete": 0,
    "totalAmountEarned": 14,
    "totalOfferPurchased": 0,
    "totalOfferSale": 0,
    "totalJobPosted": 0,
    "totalAmountSpend": 4000
  }
}
*/

  VendorDetailsModelDataUserInfo? userInfo;

  VendorDetailsModelData({
    this.userInfo,
  });
  VendorDetailsModelData.fromJson(Map<String, dynamic> json) {
    userInfo = (json['userInfo'] != null) ? VendorDetailsModelDataUserInfo.fromJson(json['userInfo']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (userInfo != null) {
      data['userInfo'] = userInfo!.toJson();
    }
    return data;
  }
}

class VendorDetailsModel {
/*
{
  "success": true,
  "message": "user info",
  "status": 200,
  "data": {
    "userInfo": {
      "id": 2,
      "email": "jyoti@yopmail.com",
      "name": "Jyoti Builders",
      "phone": "7888644412",
      "userTypes": 1,
      "descriptions": "Testing apps with different account",
      "totalJobs": 0,
      "totalHours": 0,
      "totalEarning": 0,
      "status": 1,
      "country": "India",
      "state": "Chandigarh",
      "city": "Chandigarh",
      "street": "Chandigarh Station FOB,  Daria",
      "latitude": 30.701536,
      "longitude": 76.82175,
      "isEmailVerify": 0,
      "isPhoneVerify": 0,
      "profile": "https://app.superinstajobs.com/uploads/1743437099493.0781.jpg",
      "boostTime": 1745067877,
      "isBoosted": 1,
      "isBlock": 0,
      "hourlyPrice": 10,
      "dailyPrice": 100,
      "workingHours": {
        "friday": "10:00 - 18:00",
        "monday": "10:00 - 18:00",
        "sunday": "10:00 - 18:00",
        "tuesday": "00:00 - 00:00",
        "saturday": "10:00 - 18:00",
        "thursday": "00:00 - 00:00",
        "wednesday": "10:00 - 18:00"
      },
      "favVendor": 1,
      "isBankLinked": 0,
      "remainBoostedTime": {
        "daysDifference": 30,
        "hoursDifference": 0,
        "minutesDifference": 0,
        "secondsDifference": 0
      },
      "attachments": [
        {
          "id": 3,
          "userId": 2,
          "type": 1,
          "attachments": "https://app.superinstajobs.com/uploads/1738858282015.776.jpg",
          "expireDate": 1740759080,
          "identifyId": "Doc1738858281454.jpg",
          "status": 1,
          "created": 1738858282,
          "modified": 1738858282
        }
      ],
      "category": [
        {
          "categoryId": 1,
          "categoryName": "Builders",
          "categoryImage": "https://app.superinstajobs.com/uploads/1722582520107.6833.png",
          "subCategory": [
            {
              "subCategoryId": 4,
              "name": "Painter",
              "image": ""
            }
          ]
        }
      ],
      "walletInfo": {
        "id": 2,
        "userId": 2,
        "balance": 4659,
        "currency": "NGN",
        "created": 1738858266,
        "modified": 1743506880
      },
      "notifications": {
        "userId": "2",
        "newOfferUpload": 1,
        "likeAndComment": 1,
        "directMessage": 1,
        "pauseAll": 0
      },
      "lowestPrice": 2000,
      "rating": {
        "overallRating": "0.0"
      },
      "allRatings": [
        ""
      ],
      "totalJobComplete": 0,
      "totalAmountEarned": 14,
      "totalOfferPurchased": 0,
      "totalOfferSale": 0,
      "totalJobPosted": 0,
      "totalAmountSpend": 4000
    }
  }
}
*/

  bool? success;
  String? message;
  int? status;
  VendorDetailsModelData? data;

  VendorDetailsModel({
    this.success,
    this.message,
    this.status,
    this.data,
  });
  VendorDetailsModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    status = json['status']?.toInt();
    data = (json['data'] != null) ? VendorDetailsModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    data['status'] = status;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
