///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class WalletDetailsModelData {
/*
{
  "id": 2,
  "userId": 2,
  "balance": 14449,
  "currency": "NGN",
  "created": 1738858266,
  "modified": 1748933479
}
*/

  int? id;
  int? userId;
  int? balance;
  String? currency;
  int? created;
  int? modified;

  WalletDetailsModelData({
    this.id,
    this.userId,
    this.balance,
    this.currency,
    this.created,
    this.modified,
  });
  WalletDetailsModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    userId = json['userId']?.toInt();
    balance = json['balance']?.toInt();
    currency = json['currency']?.toString();
    created = json['created']?.toInt();
    modified = json['modified']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['userId'] = userId;
    data['balance'] = balance;
    data['currency'] = currency;
    data['created'] = created;
    data['modified'] = modified;
    return data;
  }
}

class WalletDetailsModel {
/*
{
  "success": true,
  "message": "WalletInfo get successfully",
  "status": 200,
  "data": {
    "id": 2,
    "userId": 2,
    "balance": 14449,
    "currency": "NGN",
    "created": 1738858266,
    "modified": 1748933479
  }
}
*/

  bool? success;
  String? message;
  int? status;
  WalletDetailsModelData? data;

  WalletDetailsModel({
    this.success,
    this.message,
    this.status,
    this.data,
  });
  WalletDetailsModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    status = json['status']?.toInt();
    data = (json['data'] != null) ? WalletDetailsModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    data['status'] = status;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
